### ISSUE TITLE
RDataMining-02-HW.R 建議

### ISSUE THREAD

**Issue by lovelybigdata** [wush978/DataScienceAndR#116]
(1)統一與簡化文字
例：" 在training dataset上學出一個decision tree的模型" ，直接以rpart 取代"decision tree"字樣；或是"decision tree(rpart套件)"

(2)答題時的提示要更明顯，不要只寫  v1.dt2 <- NULL；舉例
解法1：
g.dt <- rpart(lettr ~ ., LetterRecognition.train, control = rpart.control(cp = 1e-04 ))
v1.dt2 <- predict(g.dt, LetterRecognition.tune, type = "class")
解法2:(巢狀式寫法)
v1.dt2  <- predict(rpart(lettr ~ ., LetterRecognition.train, control = rpart.control(cp = 1e-04 )), LetterRecognition.tune, type = "class")
是等價
但一開始看題意會誤會為一定要使用巢狀方式解法… 
如此一來在面對 xgb 時會面對巢狀Hell... 其實用解法一即可

(3)xgb的第3個模型無法直接用 rbind 對於 DMatrix 合併資料

(4)xgb在此例中用到的參數較多，要不要試著拆成2節做說明呢?? (例：rpart 與 svm 一節、xgb一節)
當然最後3個模型一起比較的確是很好的教學模式 …

**Comment by wush978** [comment]
好像除了(4)都解決了。
(4)的部分，我想等到未來重構整個教學的時候，再一併考慮囉！（所以Issues先留著）

**Comment by andyfcx** [comment]
這問題其實作業1也有，擺一行null有點讓人不知道該回答什麼
