### ISSUE TITLE
8: RDataMining-02-Classification : 80% 另一種叫出S4物件說明的方式

### ISSUE THREAD

**Issue by lovelybigdata** [wush978/DataScienceAndR#120]
由於xgboost套件使用的是R 的S4物件導向系統，除了直接輸入 help("predict,xgb.Booster-method")，若是使用 Rstudio，也可以在右下側 Help 視窗中的放大鏡中輸入 predict, 在分號之後按tab鍵，即可選擇 predict,xgb.Booster-method 再按Enter即可出現完整說明。

備註：若是  help("predict,") 按tab鍵是不會有任何回應的

**Comment by wush978** [comment]
@lovelybigdata 

在我的電腦上測不出來耶，可以跟你要一下Rstudio的版本號嗎？

Thanks

**Comment by lovelybigdata** [comment]
predict 後面要接的是逗號哦 (,) 不是句號(.) .... 在筆電上容易看錯
你試試吧  我2個系統都捉圖了

測試一：mac

> sessionInfo()
> R version 3.2.2 (2015-08-14)
> Platform: x86_64-apple-darwin14.5.0 (64-bit)
> Running under: OS X 10.11.1 (El Capitan)

![image](https://cloud.githubusercontent.com/assets/7576774/11461565/78f71156-9740-11e5-8d5c-4ed774ed0d7a.png)

測試二：win10
![image](https://cloud.githubusercontent.com/assets/7576774/11461582/d65a11b8-9740-11e5-8346-5f371e6e5b33.png)

> sessionInfo()
> R version 3.2.1 (2015-06-18)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 8 x64 (build 9200)

**Comment by wush978** [comment]
我試不出來，能跟你確認一下Rstudio 的版本嗎？不是R 的版本

**Comment by lovelybigdata** [comment]
mac 的 Rstudio : Version 0.99.486
WIN10 的 Rstudio : Version 0.99.473

**Comment by wush978** [comment]
感恩，可能server版本不支援這種用法，殘念 :(
