### ISSUE TITLE
RDataMining-03-Association-Rule: 安裝arules 失敗

### ISSUE THREAD

**Issue by haohoucla** [wush978/DataScienceAndR#128]
> install.packages('arules')

  There is a binary version available (and will be installed) but the source version is later:
       binary source
arules  1.1-9  1.3-0

trying URL 'http://cran.cnr.Berkeley.edu/bin/macosx/mavericks/contrib/3.1/arules_1.1-9.tgz'
Content type 'application/x-gzip' length 1796694 bytes (1.7 Mb)
# opened URL

downloaded 1.7 Mb

The downloaded binary packages are in
    /var/folders/7y/q51qpcj13pv65dxk05jj0jm80000gn/T//RtmpIz0tZ4/downloaded_packages
trying URL 'http://cran.cnr.Berkeley.edu/bin/macosx/mavericks/contrib/3.1/arules_1.1-9.tgz'
Content type 'application/x-gzip' length 1796694 bytes (1.7 Mb)
# opened URL

downloaded 1.7 Mb

| Nice try, but that's not exactly what I was hoping for. Try again. Or, type info() for more options.

| check_then_install("arules", "1.3.0")

**Comment by wush978** [comment]
歐，那是因為arules的套件版本太舊了。

你的R 版本是不是不夠新，所以只能安裝就版的arules呢？
