### ISSUE TITLE
DataMining-01課程

### ISSUE THREAD

**Issue by torlin** [wush978/DataScienceAndR#129]
有幾個問題：
1.最後課程結束前應該有個問題沒問完？
2.照課程內容裡所說，dbscan$cluster應該是integer（dbscan的說明文件也是這樣寫的），但我這裡在實作時，dbscan$cluster的class是numeric，也因為這個原因submit不會過。

我是在windows上安裝的，這個問題是不是應該重安裝一次fpc，還是有其他方法？

**Comment by wush978** [comment]
1. 的部份我再確認一下
2. try  `as.integer(...)`

**Comment by wush978** [comment]
不好意思，我沒有注意到1.有沒有相關問題，也沒聽到其他朋友跟我反應。

如果有更進一步的說明，麻煩提供，否則我就要關閉這個issue了。
