### ISSUE TITLE
10: RDataMining-03-Association-Rule ，mac叫出說明文件會報錯

### ISSUE THREAD

**Issue by lovelybigdata** [wush978/DataScienceAndR#132]
進度20%時，在mac底下，若照你輸入的 ?"trandactions-class" ，1個問號會報錯…
需要輸入 ??"trandactions-class" ，要有2個問號才可以
不過實務上，
我直接在 RStudio 右下側的Help中的位置直接輸入  trandactions-class 可以叫出說明文件

**Comment by wush978** [comment]
同 #138 
應該是因為typo

感恩！
