### ISSUE TITLE
11: RDataMining-04-Text-Mining,65%說明

### ISSUE THREAD

**Issue by lovelybigdata** [wush978/DataScienceAndR#134]
65%說明：
|我們用`as.character(ovid2[[1]])`看看清理後的資料。 空白都消失了。

應該是多餘的空白消失…　
正常英文句子中，單字與單字原本就會有的一個空白依然被保留。
例：
"         sed puer est, aetas mollis et apta regi." 
被轉換成了
[12] " sed puer est, aetas mollis et apta regi."

**Comment by wush978** [comment]
Thanks!

我覺得你說的很有道理，已經修正。

**Comment by wush978** [comment]
等到merge到course branch再關閉

**Comment by wush978** [comment]
#142
