### ISSUE TITLE
[問題]RDataMining-01-Clustering

### ISSUE THREAD

**Issue by jay02chen** [wush978/DataScienceAndR#136]
請問當輸入 rect.hclust(cl,k=3) 時出現
Error in rect(m[which[n]] + 0.66, par("usr")[3L], m[which[n] + 1] + 0.33,  : 
  plot.new has not been called yet
應該要怎麼解決呢>____<

**Comment by wush978** [comment]
好怪阿！感覺是繪圖裝置出了問題。

要不要先試試看plot(iris)之類的指令看看有沒有錯誤呢？

**Comment by jay02chen** [comment]
後來發現是因為要開著plot  再rect才有用
謝謝！

**Comment by wush978** [comment]
Great!
