### ISSUE TITLE
R3.2.3會跳error

### ISSUE THREAD

**Issue by YuanTingHsieh** [wush978/DataScienceAndR#137]
我發現可以更新就去更新了，
然後就error了，
好像是因為路徑問題，
就課程會去找R3.2.2的資料夾，
在我重裝回R3.2.2之後，
目前都很好。

**Comment by wush978** [comment]
感謝回報。我會查查看可能的理由

**Comment by wush978** [comment]
目前還沒有找到適合的方法來重現錯誤，所以先改成wontfix

**Comment by wush978** [comment]
方便管理，所以先把wontfix的issues關閉
