### ISSUE TITLE
10: RDataMining-03-Association-Rule ，21%文字有錯

### ISSUE THREAD

**Issue by Stromborn** [wush978/DataScienceAndR#138]
![image](https://cloud.githubusercontent.com/assets/16353157/11901737/278509f2-a5e8-11e5-97d4-60380269df6b.png)

應該是transaction才對?

**Comment by wush978** [comment]
是的，我打錯了，感謝回報

**Comment by wush978** [comment]
等到進入course branch之後再關閉

**Comment by wush978** [comment]
#142
