### ISSUE TITLE
8: RDataMining-01-Clustering--figure margins too large

### ISSUE THREAD

**Issue by lky880154** [wush978/DataScienceAndR#139]
您好
一開始就卡關了@@－－

接著請同學輸入`plot(cl)`來簡單看看hclust的結果。

/> plot(cl)
Error in plot.new() : figure margins too large

**Comment by wush978** [comment]
Hmm... 如果你先輸入plot(iris)呢？

能不能附上你的sessionInfo供我參考一下

**Comment by wush978** [comment]
和 #136 可能是同樣的問題

**Comment by lky880154** [comment]
一樣耶
/> plot(iris)
Error in plot.new() : figure margins too large

/> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.1 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] swirl_2.2.21

loaded via a namespace (and not attached):
 [1] httr_1.0.0      R6_2.1.0        magrittr_1.5    tools_3.2.2     RCurl_1.95-4.7  curl_0.9.1      yaml_2.1.13     memoise_0.2.1   crayon_1.3.1    stringi_0.5-5   stringr_1.0.0  
[12] digest_0.6.8    testthat_0.10.0 bitops_1.0-6

**Comment by wush978** [comment]
你先輸入`dev.off()`之後再度輸入`plot(iris)`呢？

**Comment by lky880154** [comment]
還是一樣＠＠
/> dev.off()
null device 
          1 

| Try again. Getting it right on the first try is boring anyway! Or, type info() for more options.

| plot(cl)

/> plot(iris)
Error in plot.new() : figure margins too large

**Comment by wush978** [comment]
如果趕時間的話，先給你一個quick solution: 試試看用我提供的server先做作業。

如果硬要解這個問題的話，可能需要調整par的參數。

請參考：
- http://stackoverflow.com/questions/12766166/error-in-plot-new-figure-margins-too-large-in-r
- http://stackoverflow.com/questions/23050928/error-in-plot-new-figure-margins-too-large-scatter-plot

如果成功的話，有空也麻煩你回報讓我知道，謝謝。

**Comment by wush978** [comment]
後續無回應了，也沒遇到其他同學反應類似的狀況，所以先關閉
