### ISSUE TITLE
[RDataMining-02] label set cannot be empty

### ISSUE THREAD

**Issue by GGGGGGGG5566** [wush978/DataScienceAndR#143]
您好：
我在寫這作業的xgboost部分時
在
# ' 3) 在training 和 tuning dataset上用xgboost或xgb.train學一個模型

xgtrainall <- xgb.DMatrix(data = model.matrix(formula, rbind(LetterRecognition.train, LetterRecognition.tune)), label = as.integer(c(LetterRecognition.train$lettr, LetterRecognition.tune$lettr)) - 1)
# '    ps. 你可以用上面建立的xgtrainall
# ' 把這個模型在testing dataset的預測結果存到變數p.bst2

g.bst <- xgb.train(xgb.param, xgtrainall, nrounds = 100, print.every.n = 10,
                   watchlist = list(val = xgtest, train = xgtrainall))

會出現
Error in xgb.iter.eval(bst$handle, watchlist, i - 1, feval) : 
  label set cannot be empty

我嘗試google都找不到解決辦法（無法確認是我的code問題還是我不小心動到題目的設定），請問這部分助教能夠幫忙解惑嗎？
（我已經砍掉重裝、重新載入題目也是一樣 QQ）

**Comment by ckchou** [comment]
我也遇到一樣的問題,
code上面的xgtest漏了 label 變數, 
改成如下就沒有 "label set cannot be empty"的錯誤了:
xgtest <- xgb.DMatrix(data = model.matrix(formula, LetterRecognition.test),
                      label = as.integer(LetterRecognition.test$lettr) - 1)

**Comment by wush978** [comment]
應該是你們誤用了。

這裡的testing dataset是要模擬實務上要做預測的資料，所以不能運用label的資訊，因為實際預測時，你不應該知道label（答案）。

請參考： https://github.com/wush978/DataScienceAndR/blob/course/RDataMining-02-Classification/scripts/RDataMining-02-HW.R#L56

這裡testing dataset只會用於prediction，不該用於training。

**Comment by ckchou** [comment]
XD 感謝!
