### ISSUE TITLE
RDataMining-01-Clustering-73%問題

### ISSUE THREAD

**Issue by arsenefrog** [wush978/DataScienceAndR#144]
如題，在這一份課程中的73%，對DBscan這個套件問了以下問題

| 請問參數`data`使用哪一種型態的物件時，需要額外設定`method`參數為`"dist"`？

1: numeric vector
2: dist-object
3: dissimilarity matrix
4: data matrix
5: data.frame

正解給2

但根據文件
Arguments

data  
data matrix, data.frame, dissimilarity matrix or dist-object. Specify method="dist" if the data should be interpreted as dissimilarity matrix or object. Otherwise Euclidean distances will be used.

似乎2或3都應該要設定，不知是否是我誤解，還請wush大大確認

**Comment by wush978** [comment]
@arsenefrog 

你是對的，我題目寫錯了。

感謝回報。

**Comment by wush978** [comment]
#142
