### ISSUE TITLE
RDataMining-02-Classification-12%文字敘述有誤

### ISSUE THREAD

**Issue by arsenefrog** [wush978/DataScienceAndR#145]
課程內容：
[quote]
  |==============                                                                                                      |  12%

| 根據`rpart`的說明文件，我們剛剛輸入的： `cfit <- rpart(pgstat ~ age, data = stagec, method = "class")`中
| 的`stagec`是對應到`rpart` 函數的哪一個參數呢？
[\quote]

但事實上，剛剛輸入的應該是cfit <- rpart(pgstat ~ age + eet + g2, data = stagec, method = "class")，跟這邊的敘述不一致。

非常minor的問題，不影響學習~回報一下

**Comment by wush978** [comment]
@arsenefrog 

感恩！

**Comment by arsenefrog** [comment]
再來一些minor bugs:
同一份作業45%的地方，submit()的括號不見囉。
同一份作業65%~66%的地方，nrounds的s也不見了。(以上都是typo)

**Comment by arsenefrog** [comment]
(繼續把同一份作業的bug回在這裡)
同一份作業91%的地方：
[quote]
svm 在學習時，可以依據應用解決不同的問題。這取決於目標的型態。舉例來說，如果我們 使用`svm(Species ~ .,
| iris)`，這裡的預測目標就是`iris$Species`這個變數了。請問同學， 這個變數的型態（class）是什麼？
[\quote]

這裡的答案應該是factor(或是直接打class(iris$Species)?)，我手賤不小心打成vector，結果也過了。

**Comment by wush978** [comment]
感謝回報。

你有沒有興趣留個名字，我把你放到wiki上的貢獻者中的reviewer list呢？ :P

**Comment by wush978** [comment]
fixed

**Comment by wush978** [comment]
#142
