### ISSUE TITLE
RDataMining-02-Classification 同一份HW code在不同環境下執行結果不同

### ISSUE THREAD

**Issue by arsenefrog** [wush978/DataScienceAndR#146]
這個bug很謎...
接近HW死線，但submit()一直沒過。和朋友討論之後覺得我們的code長得幾乎一樣，
朋友的code在他的環境下(OS X Yosemite, R3.2.2)submit通過，
我在windows 7, R3.2.2 之下跑同一份作業code，結果是v1.dt2 is wrong! Try again.
(由於是作業的關係，就不把code附上來了)

有試過關掉swirl重開，關掉R重開，清掉workspace都得到一樣的結果。
之前有聽說windows會有一些不穩定的狀況，但我使用以來除了perl之類的警告都沒有問題，
想不到這次會這樣。不知道Wush大之前是否有接到類似的狀況反應?

**Comment by wush978** [comment]
@arsenefrog 你是第一個回報這類問題的。

請問是哪一份作業呢？

**Comment by arsenefrog** [comment]
RDataMining-02-Classification 最後面的作業，就是RDataMining裡面最難的那份。
剛剛試著重新安裝swirl之後再試一次，但仍然得到一樣的結果。

**Comment by arsenefrog** [comment]
因為作業死線還沒過，所以我暫時不打算直接貼code。
不過，issue區有另一位大大對這份作業提出建議 (#116)
那一篇裡面的語法應該是對的，但我的v1.dt2 的code跟他一樣，卻還是得到v1.dt2 is wrong.

**Comment by wush978** [comment]
如果你直接看原始碼，可以看到檢驗的方法。這部份也許可以給你更多的提示。

或者你可以把你的語法在 [![Gitter](https://badges.gitter.im/wush978/DataScienceAndR.svg)](https://gitter.im/wush978/DataScienceAndR?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) 上私訊我。

**Comment by wush978** [comment]
c3981ad: 將答案push上CI做測試

**Comment by wush978** [comment]
#142
