### ISSUE TITLE
Error on Lesson Menu - 1: appveyor.yml

### ISSUE THREAD

**Issue by ningchencontact** [wush978/DataScienceAndR#15]
"appveyor.yml" is supposedly not for students so that it would be confused when it appears in the lesson menu. Otherwise,when users select 1: appveyor.yml in lesson menu, it leads to an error," Error in file(con, "r") : invalid 'description' argument| Leaving swirl now. Type swirl() to resume."

Thus, I suggest to remove "1: appveyor.yml" from lesson menu.

Ning

**Comment by wush978** [comment]
resolved!

Thank you
