### ISSUE TITLE
rdataengineering-01 做到一半當掉，而且回不去

### ISSUE THREAD

**Issue by hjhsu** [wush978/DataScienceAndR#159]
![image](https://cloud.githubusercontent.com/assets/8024751/12392286/d0908a0a-be28-11e5-9d0d-07b3f8b3b0e5.png)

**Comment by hjhsu** [comment]
重新開 swirl() 會變下面這樣
![image](https://cloud.githubusercontent.com/assets/8024751/12392323/145842c8-be29-11e5-9202-287c95bbf320.png)

**Comment by wush978** [comment]
@hjhsu
如果照以下方式更新套件：
`install.packages("swirl", repos = "http://wush978.github.io/R", type = "source")`
再跑一次，請問還會不會出錯呢？

**Comment by hjhsu** [comment]
我用你上面的方法更新了套件，一樣會出錯喔

**Comment by hjhsu** [comment]
我又重新裝了一次，到了該步驟(21%)，我用 skip()
出下列 error
Error in eval(expr, envir, enclos) : 
  could not find function ".read.table.big5"

程式自動跳出 swirl ，然後我重新啟動 swirl
跳下列 error
Error in assign("hospital_path", .get_path("DataGov25511.csv"), envir = globalenv()) : 
  could not find function ".get_path"

**Comment by wush978** [comment]
這些錯誤是因為 https://github.com/wush978/DataScienceAndR/blob/dev/rdataengineer-01/.initCourse.R 這個檔案沒有載入，而這些檔案是要透過我hack過得swirl才會做載入

**Comment by wush978** [comment]
@hjhsu 能麻煩你檢查一下packageVersion("swirl")的值嗎？感恩

**Comment by wush978** [comment]
```
> packageVersion("swirl")
[1] ‘2.3.1.1’
> 
```

**Comment by hjhsu** [comment]
> packageVersion("swirl")
> [1] ‘2.3.1.1’

**Comment by wush978** [comment]
confirmed, 我檢查一下，感恩
