### ISSUE TITLE
斷句很奇怪～～

### ISSUE THREAD

**Issue by ningchencontact** [wush978/DataScienceAndR#16]
比如以下題目 斷句會影響對文字的了解
建議整理斷句

| 在R
| 中，`c()`可以接受任意數量的的向量參數，並且會依照順序把它們
| 串接成一個單一向量。舉例來說：`c(x,
| 1)`會在剛剛我們建立的x 後面 再接一個1
| 。而`c(x, 2, 3)`則會在x 之後接上2 和3
| 。請同學依照這個要領，
| 撰寫一個expression，內容是建立一個在x
| 後面接上x 的向量。

**Comment by wush978** [comment]
也許可以用auto-hint來解決。

等待測試

**Comment by wush978** [comment]
我拿這個問題無解耶，唉

可能要到swirl改code才能解決

**Comment by wush978** [comment]
在理解swirl對斷句的處理之前，無法修正。

另外因為我覺得這件事情的Priority相對不高，可能要等完整的教材做完之後，再找時間回來修。

**Comment by wush978** [comment]
現在Issue越來越多了，所以先把wontfix的關閉
