### ISSUE TITLE
一些來自 taichi43 的comments

### ISSUE THREAD

**Issue by wush978** [wush978/DataScienceAndR#161]
Thanks, @taichi43

1.
這是我在載入課程的時候不斷出現的訊息，
warning messages from top-level task callback 'mini'
Warning messages:
1: In grepl("\n", lines, fixed = TRUE) :
  input string 1 is invalid in this locale
2: In grepl("\n", lines, fixed = TRUE) :
  input string 2 is invalid in this locale
3: In grepl("\n", lines, fixed = TRUE) :
  input string 5 is invalid in this locale
4: In grepl("\n", lines, fixed = TRUE) :
  input string 8 is invalid in this locale
5: In grepl("\n", lines, fixed = TRUE) :
  input string 11 is invalid in this locale
6: In grepl("\n", lines, fixed = TRUE) :
  input string 1 is invalid in this locale
7: In grepl("\n", lines, fixed = TRUE) :
  input string 2 is invalid in this locale
8: In grepl("\n", lines, fixed = TRUE) :
  input string 5 is invalid in this locale
9: In grepl("\n", lines, fixed = TRUE) :
  input string 8 is invalid in this locale
10: In grepl("\n", lines, fixed = TRUE) :
  input string 11 is invalid in this locale
1. 
   RBasic 3 HW
   #' 請同學找出這個物件的"型態"。你的答案只可能是：「character」、「numeric」或「list」

3.
RBasic 5 
反矩陣用解方程式來說明較佳，解三元一次方程式的問題之類的

4.
RBasic 5 HW 
建議可以先引回歸的那段，會比較清楚接下來要做什麼

5.
RBasic 5 HW
建立Y的過程說明要調整，比較好的方式是在練習的時候就加入矩陣乘行向量會得到行向量的概念
建議接在這個的後面
- Class : cmd_question
  Output: 另外當兩個向量使用`%*%`做運算，會得到他們的內積。舉例來說：`1:3 %*% 1:3`會得到什麼呢？請同學試試看。
  CorrectAnswer: 1:3 %_% 1:3
  AnswerTests: omnitest('1:3 %_% 1:3')
- Class : cmd_question
  Output: 另外當矩陣乘向量的時候，單一向量會被視為行向量，最後會得到矩陣每個列和單一向量的內積，形成一個新的行向量。舉例來說：`matrix(1:9,3,3) %*% 1:3`會得到什麼呢？請同學試試看。
  CorrectAnswer: matrix(1:9,3,3) %_% 1:3
  AnswerTests: omnitest('matrix(1:9,3,3) %_% 1:3')
# ' 我們稱`X[,1]`為x1, `X[,2]`為x2, `X[,3]`為x3
# ' 向量y 的值是 x1 \* beta[1] + x2 \* beta[2] + x3 \* beta[3]
# ' 請用矩陣乘法`%*%`算出向量y
# ' ps. class(y) 應該要是 "matrix"
# '     dim(y) 應該是 c(10, 1)

y <-  X %*% beta
1. 
   RBasic 6 建議加入head

7.
RBasic 6 建議加入ncol nrow 在HW會用到

8.
RBasic 6 HW 
幾個字的調整
# ' CO2 共有很多很多列（answer3）
# ' 請從CO2 中挑出一些列，滿足以下的條件：
# ' 這些列的uptake直，超過全部CO2"平均"的uptake值
# ' "（`answer4`）"

9.
RBasic 7 HW

我在執行作業的時候，嘗試用readLines，出現下面的warning

readLines(file(orglist.path, encoding = "UTF-16"),n=1)
[1] "\"機關代碼\",\"機關名稱\",\"郵遞區號\",\"機關地址\",\"機關電話\",\"主管機關代碼\",\"主管機關名稱\",\"傳真\",\"機關生效日期\",\"機關裁撤日期\",\"機關層"
Warning message:
In readLines(file(orglist.path, encoding = "UTF-16"), n = 1) :
  incomplete final line found on 'C:\Users\taich_000\Documents\R\win-library\3.1\swirl\Courses\DataScienceAndR\RBasic-07-Loading-Dataset\orglist-100.CSV'

不曉得有沒有解決的方式
1. 用解方程式的想法來描述Matrix/Array的問題

**Comment by wush978** [comment]
目前懷疑1.的問題和作業系統有關

在Windows7上會發生，但是在Windows10上不會

（需要確認）

**Comment by SInnget** [comment]
@wush978 目前使用win10，問題一中的訊號經常出現，至少載入新課程時既會出現一次。交作業的時候也會出現。
