### ISSUE TITLE
沒有解釋何謂expression

### ISSUE THREAD

**Issue by ningchencontact** [wush978/DataScienceAndR#17]
此題目中 未解釋何謂是expression(前幾題也沒解釋)
建議在此題前面加上assignment 跟 expression的解釋
以方便學員了解跟作答

| 在R
| 中，c()可以接受任意數量的的向量參數，並且會依照順序把它們
| 串接成一個單一向量。舉例來說：c(x, | 1)會在剛剛我們建立的x 後面 再接一個1
| 。而c(x, 2, 3)則會在x 之後接上2 和3
| 。請同學依照這個要領，
| 撰寫一個expression，內容是建立一個在x
| 後面接上x 的向量。

**Comment by wush978** [comment]
這其實牽涉到閱讀教材的順序。
我應該要在前面標示1, 2, 3, ...

**Comment by wush978** [comment]
我記得在 Introduction 的時候有解釋expression，請 @agogomei01  幫我看看如果加上閱讀順序後（具體的更改內容在 #22 ），是否算是解決這個問題。
