### ISSUE TITLE
RDataEngineer-05-06 中題目敘述有誤

### ISSUE THREAD

**Issue by jackyeh168** [wush978/DataScienceAndR#170]
![default](https://cloud.githubusercontent.com/assets/9561838/12472724/18453c64-c046-11e5-9153-1b8b42c95e76.png)

敘述中寫 "並且最後只留下month 與 `mortage_total_bal`兩個欄位"
然而下方的檢查程式卻是檢查 `mortgage_bal`是否為空

**Comment by wush978** [comment]
Thanks

**Comment by wush978** [comment]
已經透過 #178 修復了

**Comment by wush978** [comment]
感恩， @jackyeh168
