### ISSUE TITLE
comments on RDataEngineer-06-Join 

### ISSUE THREAD

**Issue by hjhsu** [wush978/DataScienceAndR#177]
25% 
在剛剛航空公司名稱的範例中，`x`是`flights`，`y`是`airlies`。
airlies => airlines

51% 小魔王的註解 
請依據year:day, hour, origin, hour比對`flights`和`weather`
兩個 hour

大魔王，假如有指定哪個欄位要叫什麼名稱，是不是寫在每一項 answer 前面的說明比較好？

**Comment by wush978** [comment]
Thanks, @hjhsu 

大魔王的部分我想想

**Comment by hjhsu** [comment]
其實你有指定第一欄要放啥、第二欄要放啥，不然就是檢查的部分用column index；我也只是提一下，因為我錯了好幾次，才發現說你在 stopifnot 那邊有寫要檢查 colname.....

**Comment by wush978** [comment]
這波寫完就會有大魔王的樣板和SOP，到時後`stopifnot`應該是所有大魔王都要放的。(學生不用`submit()`就知道自己錯了)
說明細節，就統一由大魔王的相關說明搞定，而不是在個別的大魔王中說明。
