### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ningchencontact** [wush978/DataScienceAndR#18]
The italic and bold words are typo.
| 不是所有的運算都是向量式的。如果給定一個向量x
| , max(x)會傳回x
| 中_**最小**_的值，而min(x)會傳回x _**最大**_ 的值。

---

| 另外我們也跟各位介紹一個更_**范用**_產生向量的方式：`seq`。
范用=>泛用
| `seq(1, 10)` 在R
| 中，其實就是`1:10`。請試試看輸入`seq(1:10)`

**Comment by wush978** [comment]
已經修正，感謝
