### ISSUE TITLE
 RVisualization-02-Two-Variables-Visualization 選擇後跳出 swirl

### ISSUE THREAD

**Issue by hjhsu** [wush978/DataScienceAndR#187]
無法開啟該課程，下面是錯誤訊息

Selection: 23
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
In addition: Warning messages:
1: In grepl("\n", lines, fixed = TRUE) :
  input string 15 is invalid in this locale
2: In grepl("\n", lines, fixed = TRUE) :
  input string 16 is invalid in this locale

| Leaving swirl now. Type swirl() to resume.

**Comment by wush978** [comment]
Fixed via: 06b1f9808e43a42a1fe33faa23f1a2deeb5b3388

Thanks.
