### ISSUE TITLE
comments on RVisualization-02-Two-Variables-Visualization

### ISSUE THREAD

**Issue by hjhsu** [wush978/DataScienceAndR#188]
31%
dat2 <- summarise(group_by(hsb, sex, schtyp), math.avg=mean(math))
dat2 <- group_by(hsb, sex, schtyp) %>% summarise(math.avg=mean(math))
*既然上課有講 pipe 要不要考慮把指令改成 pipe 形式？

42%
dat3 <- group_by(hsb, race) %>% summarise(read.med=median(read))
*同31%

64%
| 在`boxplot`上加入圖例`legend`。請同學輸入以下指令： `legend("top", c("private", "public"), fill=c("darkblue", "gold"))`

> legend("top", c("private", "public"), fill=c("darkblue", "gold"))
> | Almost! Try again. Or, type info() for more options.
> | legend("topleft", c("private", "public"), fill=c("darkblue", "gold"))

*照著一開始的提示打，會說做錯，然後 hint 指令的圖例位置與原本的要求不同 top -> topleft

 67%
| 因為兩組數據的boxplot結果高度重疊，所以判斷公立學校與私立學校的學生在數學表現上沒有明顯差距。
*這邊沒有講 testing 行嗎？雖然說這邊帶 testing 進來太難了，但是感覺這樣講好像太籠統了一點？因為從圖上看，私立學校跟公立學校雖然最高分相同，但是box 整體來說高一些。

**Comment by wush978** [comment]
@hjhsu 感謝你的意見回饋。

關於31%, 42%的部分我覺得還好，考量到未來有可能同學是跳關直接做RVisualization-02，所以目前還是先維持原樣。
64%已經修正。
67%當天同學也沒有人問這題，所以我先保留。

未來RVisualization應該是要重構（重寫），所以先更新比較嚴重，在64%的錯誤。
