### ISSUE TITLE
cannot join Selection: 24 RVisualization-03-ggplot2

### ISSUE THREAD

**Issue by ningchencontact** [wush978/DataScienceAndR#193]
當我進行到這一步

Selection: 24
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  could not find function ".get_path"

| Leaving swirl now. Type swirl() to resume.

打完 swirl() 之後，就回到 問我名字的畫面

**Comment by wush978** [comment]
經確認是swirl版本的問題。
