### ISSUE TITLE
ggplot2 27%說明饒口不清楚

### ISSUE THREAD

**Issue by ningchencontact** [wush978/DataScienceAndR#195]
| `geom_bar`的`stat`和`position`參數則會影響繪圖的結果。這兩個參數則是`geom_bar`所
| 特有的。ggplot2把共用概念的繪圖參數，如：`x`、`y`和`fill`這些在大部分的圖表都會用到的參數
## 原先語意不清楚，建議可以改成以下的寫法，並在前面加上一個geom_bar(stat...)等的例子作輔助說明

請注意 ggplot2 把 `x`、`y`和`fill`等共用圖表參數都放在aes中，例如：ggplot(infert,aes(x=education))中的aes(x=education)定義了圖層的X軸，所以，X軸在ggplot2是共用的圖表參數。
geom_bar的`stat`和`position`參數，只控制長條圖的呈現，是geom_bar特有參數，例如：....(建議在此處說明前要先有geom_bar(stat...)等的例子作輔助說明。

**Comment by wush978** [comment]
更改了說明順序，Thanks
