### ISSUE TITLE
ggplot2 33%語意不清

### ISSUE THREAD

**Issue by ningchencontact** [wush978/DataScienceAndR#196]
> | 透過剛剛的比較，我們可以看出`position`的用途就是：當有第二個類別出現的時候，我們是要把
> | 所有的個數依照第一個類別疊加在同樣的長條上(重點在比較第一個類別)，還是把它們肩並肩站著
> | 呢(重點在比較第一類別中的第二個類別)？

以上語意不清，建議可以用以下修改

> 請比較用 g + geom_bar(aes(x = sex,fill=race))；g + geom_bar(aes(x = sex, fill = race), position = "dodge") 做出圖的差異性。
> 無position，長條圖型會將race推疊呈現，有position，長條圖會將race錯開呈現。也由於position只控制長條圖，所以，position是geom_bar特有參數。

**Comment by wush978** [comment]
Thanks
