### ISSUE TITLE
ggplot2 37% 做不出來

### ISSUE THREAD

**Issue by ningchencontact** [wush978/DataScienceAndR#197]
> | 請同學利用`group_by`和`summarise`計算各種sex類別的個數。
> 
> > hsb %>%
> > - group_by(sex) %>%
> > - summarise(a=n())
> >   Source: local data frame [2 x 2]
> 
> ```
>  sex     a
> ```
> 
>   (fctr) (int)
> 1 female   109
> 2   male    91

我認為我答案是對的，但是，不給過~~

**Comment by wush978** [comment]
你確認看看colnames呢？

**Comment by ningchencontact** [comment]
> hsb %>%
> - group_by(sex) %>%
> - summarise(count=n())
>   Source: local data frame [2 x 2]

```
 sex count
```

  (fctr) (int)
1 female   109
2   male    91

> 我有改了一下 欄位應該是對的 但還是過不去

**Comment by wush978** [comment]
我也不知道為什麼你過不去（但是其他人可以）

麻煩貼上你的錯誤訊息喔！

ps. 沒過的話，應該會印出錯誤訊息

**Comment by ningchencontact** [comment]
我按skip 跟 "Press Enter when you are ready to continue..."

 hsb %>%
- group_by(sex) %>%
- summarise(count=n())
  Source: local data frame [2 x 2]
  
   sex count
  (fctr) (int)
  1 female   109
  2   male    91
  
  > skip()

| I just sourced the following script, which demonstrates one
| possible solution.

Press Enter when you are ready to continue...

| Not exactly. Give it another go.

> skip()

| I just sourced the following script, which demonstrates one
| possible solution.

Press Enter when you are ready to continue...

| You're close...I can feel it! Try it again.

**Comment by wush978** [comment]
1. 檢查一下有沒有存檔喔
2. 檢查一下檔案裡面的程式碼有沒有syntax error

方式：ctrl + A 後把內容通通送到console, 看R有沒有噴錯

**Comment by wush978** [comment]
@agogomei01 
我沒收到其他同學反應有問題，所以就先關閉了
