### ISSUE TITLE
看不到作業內容

### ISSUE THREAD

**Issue by cmelo1515** [wush978/DataScienceAndR#199]
我上完第二課時，想要做作業，但是發現無法顯示中文字，照著下述的方法做，仍無法改善

(如果同學在檔案中看到亂碼，請使用Rstudio 左上角的File -> Reopen With Encoding... ->
 選取：UTF-8)

請問該怎麼解決呢謝謝

**Comment by wush978** [comment]
就我的經驗，學生只要依照這樣的動作就可以了。

能麻煩你拿Hello-DataScienceAndR課程做測試看看嗎？

**Comment by cmelo1515** [comment]
有的，我有做了Hello-DataScienceAndR測試，有出現「test-script.R」的檔案，可是我仍然沒看到中文字，我有依照順序點選Rstudio左上角的File-> Reopen With Encoding... -> 選取：UTF-8，發現沒有：「#這是測試功能的檔案」等字眼，請問是缺少UTF-8相關的套件嗎?

**Comment by wush978** [comment]
你的作業系統是中文版嗎？有中文字型嗎？

**Comment by cmelo1515** [comment]
是的，是WIN10中文版

**Comment by wush978** [comment]
你是第一個沒辦法透過這樣的步驟，讓原始碼中的中文正確顯示的。所以我也很好奇你遇到的狀況，並且很想幫你解決。

為了節省我們的時間，首先還是麻煩你確認一下，進入Hello-DataScienceAndR後依照影片1分33秒做操作。影片網址：https://youtu.be/fcd6zSk0yd8?t=1m33s

如果不行的話，麻煩在R輸入`sessionInfo()`後把整個螢幕的畫面截下來，貼到這裡（你可以上傳到Imgur）

**Comment by cmelo1515** [comment]
我有照著影片的步驟去做，我輸入skip()後，雖然有出現test-script.R這個檔案，但是裡面卻沒有內容(連亂碼都沒有)，然後也有Reopen With Encoding再選UTF-8，還是沒辦法QQ，麻煩大大幫助了~~

http://imgur.com/d6orAq8

http://imgur.com/2VfuFfz

**Comment by wush978** [comment]
你的使用者名稱是不是中文呢？

**Comment by wush978** [comment]
之前有同學因為使用者名稱是中文，導致R在複製檔案到`tempdir()`的時候會發生錯誤，因此造成檔案空白的狀況

**Comment by wush978** [comment]
@hjhsu 不知道你們後來是怎麼解決這個問題呢？

**Comment by cmelo1515** [comment]
對耶!!!!感謝大大!!!!!  我把使用者名稱改成英文後就可以了!!!!!(不過我電腦怪怪的，使用者名稱費了一番功夫才剛改好哈哈哈)

**Comment by wush978** [comment]
Great
