### ISSUE TITLE
RBasic-03-Data-Structure-Object題目建議修改如下

### ISSUE THREAD

**Issue by jerrywu2013** [wush978/DataScienceAndR#246]
題目原為
# ' 請同學找出`pca`這個向量的長度

answer2 <- length(pca)
# ' 請同學找出`pca`的名字

answer3 <- names(pca)
# ' `pca` 的元素中，有一個是各個principal components的standard deviations。
# ' 請同學參考`help(prcomp)`的說明，將各個principal components的standard deviations
# ' 的值取出，存到答案中。

answer4 <- <填寫你的程式碼>
# ' `pca` 的元素中，有一個是做PCA的中心(center)。請同學參考`help(prcomp)`的說明，
# ' 把該元素取出，存到答案中。

answer5 <- <填寫你的程式碼>
# 

建議修正如下：
# ' 請同學撰寫找出`pca`這個向量的長度的「指令」

answer2 <- length(pca)
# ' 請同學撰寫找出`pca`的名字的「指令」

answer3 <- names(pca)
# ' `pca` 的元素中，有一個是各個principal components的standard deviations。
# ' 請同學參考`help(prcomp)`的說明，撰寫將各個principal components的standard deviations
# ' 的值取出的「指令」。

answer4 <- <填寫你的程式碼>
# ' `pca` 的元素中，有一個是做PCA的中心(center)。請同學參考`help(prcomp)`的說明，
# ' 撰寫把該元素取出的「指令」。

answer5 <- <填寫你的程式碼>

**Comment by wush978** [comment]
感恩 :D 已經修改
