### ISSUE TITLE
RDataMining-04-Text-Mining 88% 找不到 achillem

### ISSUE THREAD

**Issue by BoboLiao** [wush978/DataScienceAndR#247]
|讓我們用`inspect(tdm[1,])`來看看這個矩陣的第一列

> inspect(tdm[1,])
> | 我們看到一個字：`achillem,`，而且只有出現在`ovid_1.txt`為1 其他為0。
> | 這其實就是TermDocumentMatrix的意思。它利用空格切出terms，然後去紀錄
> | 每一個terms出現在哪些文件(docuemtns)中的次數。

但inspect(tdm[1,])中沒有"achillem",只有" 'haec "
"achillem"似乎在 inspect(tdm[4,])裡面才對

**Comment by BoboLiao** [comment]
>inspect(tdm[1,])
<<TermDocumentMatrix (terms: 1, documents: 5)>>
Non-/sparse entries: 1/4
Sparsity           : 80%
Maximal term length: 5
Weighting          : term frequency (tf)

       Docs
Terms   ovid_1.txt ovid_2.txt ovid_3.txt ovid_4.txt ovid_5.txt
  'haec          0          0          0          1          0

**Comment by wush978** [comment]
在我家的電腦，卻跑出 `achillem`... XD

Anyway, 敘述已經修改過了，感謝
