### ISSUE TITLE
RBasic Section 4 cant open

### ISSUE THREAD

**Issue by atomchung** [wush978/DataScienceAndR#249]
當進入課程4時出現這個畫面

Selection: 4
Error in is.data.frame(data) : 
  lazy-load database '/Library/Frameworks/R.framework/Resources/library/datasets/data/Rdata.rdb' is corrupt
In addition: Warning messages:
1: In is.data.frame(data) : restarting interrupted promise evaluation
2: In is.data.frame(data) : unknown type in R_decompress3

不知道如何處理

謝謝

**Comment by wush978** [comment]
請問重灌課程後有幫助嗎？

**Comment by atomchung** [comment]
後來重開課程後,就可以了

謝謝

**Comment by wush978** [comment]
感謝回報
