### ISSUE TITLE
Cannot load youbike dataset

### ISSUE THREAD

**Issue by ningchencontact** [wush978/DataScienceAndR#26]
| 接著，請同學輸入：`rs <-
| dataSetMetadataSearch(q = "youbike")`來：
| 1. 搜尋youbike的資料源；2.
| 將結果儲存到變數rs之中

> rs<-dataSetMetadataSearch(q = "youbike")
> Error in curl::curl_fetch_memory(url, handle = handle) : 
>   Failure when receiving data from the peer
> rs=dataSetMetadataSearch(q = "youbike")
> Error in curl::curl_fetch_memory(url, handle = handle) : 
>   Failure when receiving data from the peer

I am stuck after typing skip(). It shows unstopped "download red light"

**Comment by lovelybigdata** [comment]
我在 win10也遇到相同現象，請手動自行載入 libray(curl) 即可解決，若先前無安裝此套件，請自行安裝；在docker化的 rstudio server 則無此問題

**Comment by wush978** [comment]
謝謝告知，我考慮在該課程之前讓同學載入`library(curl)`

**Comment by wush978** [comment]
#73
