### ISSUE TITLE
00-Hello chat() 錯誤: 沒有這個函數 "chat"

### ISSUE THREAD

**Issue by unityculture** [wush978/DataScienceAndR#262]
Hi all : 

在執行`00-Hello`這章節時，要求輸入`chat()`時顯示錯誤`錯誤: 沒有這個函數 "chat"
`

安裝swirl的過程中按照：
1. 打開R ，執行：source("http://wush978.github.io/R/init-swirl.R")
2. 輸入library(swirl);swirl()後即進入教學環境。

相關的Log請[參考](https://docs.google.com/document/d/1ej9sFH9dsg27U68FmWfV80zisQLksG3RRBOvskx9DCk/edit?usp=sharing)

**Comment by wush978** [comment]
Hmm... 我的電腦上無法重現耶。

你重新做一下以下動作：
1. 重開R
2. 重新 source("http://wush978.github.io/R/init-swirl.R")
3. 再進行一次Hello DataScienceAndR

我的猜測是，因為你是在課程進行到一半的時候安裝swirl，所以可能混雜到舊版的檔案

**Comment by unityculture** [comment]
重新開啟R之後再執行上述動作，成功解決！
