### ISSUE TITLE
02-RDataEngineer-05

### ISSUE THREAD

**Issue by JohnsonHsieh** [wush978/DataScienceAndR#264]
在關卡 21%

```
| 如果我們要使用RBasic系列所所使用的語法，要如何得到同樣的結果呢？請同學
| 試著寫寫看。提示：兩個布林比較和一個`[`
```

這邊會跳出小魔王關 02-RDataEngineer-05-01.R，需要完成後在console 輸入 submit()，但是題目說明沒有提示要 submit()，建議修改如下

```
| 如果我們要使用RBasic系列所所使用的語法，要如何得到同樣的結果呢？請同學
| 試著寫寫看。提示：兩個布林比較和一個`[`，請同學修改02-RDataEngineer-05-01.R之後，在在console 輸入 submit()
```

**Comment by wush978** [comment]
有呀！

> | 如果我們要使用RBasic系列所所使用的語法，要如何得到同樣的結果呢？請同學
> | 試著寫寫看。提示：兩個布林比較和一個`[`。這題請在檔案：RDataEngineer-05-01.R 中作答，完成後請存檔並切換到console中輸入：submit()
