### ISSUE TITLE
RBasic and REngineer小小錯字與建議

### ISSUE THREAD

**Issue by chengu1024** [wush978/DataScienceAndR#269]
大大以下為我遇到的一點點小狀況，辛苦了！
1.  | 在R 中，`rep`也可以作用在一個序列上。如果使用者是了argument `times`定值， 那R
       | 會將整個序列重複`times`次，然後接起來。請同學試試看： `rep(x, times = 2)`

--> 怪怪的？是不是應該打成”試”或”鍵入”？
1.  在01-RBasic-02-Data-Structure-Vectors關卡12的時候(不是所有的運算都是向量式的。如果給定一個向量x,max(x)會傳回x中最大的值，而min(x)會傳回x最小的值。有時候在分析的時候，我們如果想要知道數值的範圍，這兩個函數就很有用。請同學寫一個expression來建立一個兩個值的向量，而且第一個值是x的最小值，第二個是x的最大值。)

--> 因為我不小心將x給蓋掉，輸入了x <- c(min(x),max(x))，導致我關卡66會出現bug，必須重頭開始闖關
1.  在01-RBasic-04-Factors關卡18

--> 正解為grades_factor <- factor(grades, ordered = TRUE, levels = c("C","B","A"))，但是我打grades_factor <- factor(grades, ordered = T, levels = c("C","B","A"))一樣可以跑出正解，只是系統會告訴我不完全正確。
1.  在01-RBasic-06-List-DataFrame的大魔王關卡，
   #' CO2 共有很多很多列（answer3）
   #' 請從CO2 中挑出一些列，滿足以下的條件：
   #' 這些列的uptake直，超過全部CO2"平均"的uptake值
   #' （`answer4`）

「直」-->「值」
1.  在02-RDataEngineer-04-Database關卡71，
   之後，就算我們斷線從連，CO2也不會回來了。

「從」-->「重」
1.  在02-RDataEngineer-05-Data-Manipulation關卡17，
   | 如果我們要使用RBasic系列所所使用的語法，要如何得到同樣的結果呢？請同學
   | 試著寫寫看。提示：兩個布林比較和一個`[`

--> 有一點吹毛求疵…可是因為題目敘述沒有告訴我要將答案寫在上面的script，所以我一直在console試了好一會兒才發現，可能麻煩可以在敘述提醒一下同學！
1.  在02-RDataEngineer-06-Join關卡50中，
   | 我們會看到`df1`資料都有保留下來。（結果的`x`欄的值為`c(1,2)`）
   | 而第二筆資料，因為對不到`y`的資料，所以`a`與`b`的欄位都是NA

-->  應該是對不到`x`的第二筆資料？

**Comment by wush978** [comment]
先標注一下記號

> 大大以下為我遇到的一點點小狀況，辛苦了！

## 1

>    | 在R 中，rep也可以作用在一個序列上。如果使用者是了argument times定值， 那R | 會將整個序列重複times次，然後接起來。請同學試試看： rep(x, times = 2)
> 
> --> 怪怪的？是不是應該打成”試”或”鍵入”？

## 2

> ```
> 在01-RBasic-02-Data-Structure-Vectors關卡12的時候(不是所有的運算都是向量式的。如果給定一個向量x,max(x)會傳回x中最大的值，而min(x)會傳回x最小的值。有時候在分析的時候，我們如果想要知道數值的範圍，這兩個函數就很有用。請同學寫一個expression來建立一個兩個值的向量，而且第一個值是x的最小值，第二個是x的最大值。)
> ```
> 
> --> 因為我不小心將x給蓋掉，輸入了x <- c(min(x),max(x))，導致我關卡66會出現bug，必須重頭開始闖關

## 3

> ```
> 在01-RBasic-04-Factors關卡18
> ```
> 
> --> 正解為grades_factor <- factor(grades, ordered = TRUE, levels = c("C","B","A"))，但是我打grades_factor <- factor(grades, ordered = T, levels = c("C","B","A"))一樣可以跑出正解，只是系統會告訴我不完全正確。

## 4

> ```
> 在01-RBasic-06-List-DataFrame的大魔王關卡， #' CO2 共有很多很多列（answer3） #' 請從CO2 中挑出一些列，滿足以下的條件： #' 這些列的uptake直，超過全部CO2"平均"的uptake值 #' （answer4）
> ```
> 
> 「直」-->「值」

## 5

> ```
> 在02-RDataEngineer-04-Database關卡71， 之後，就算我們斷線從連，CO2也不會回來了。
> ```
> 
> 「從」-->「重」

## 6

> ```
> 在02-RDataEngineer-05-Data-Manipulation關卡17， | 如果我們要使用RBasic系列所所使用的語法，要如何得到同樣的結果呢？請同學 | 試著寫寫看。提示：兩個布林比較和一個[
> ```
> 
> --> 有一點吹毛求疵…可是因為題目敘述沒有告訴我要將答案寫在上面的script，所以我一直在console試了好一會兒才發現，可能麻煩可以在敘述提醒一下同學！

## 7

> ```
> 在02-RDataEngineer-06-Join關卡50中， | 我們會看到df1資料都有保留下來。（結果的x欄的值為c(1,2)） | 而第二筆資料，因為對不到y的資料，所以a與b的欄位都是NA
> ```
> 
> --> 應該是對不到x的第二筆資料？

我等等一個個處理，謝謝你的回報

**Comment by wush978** [comment]
## 1

>   | 在R 中，rep也可以作用在一個序列上。如果使用者是了argument times定值， 那R | 會將整個序列重複times次，然後接起來。請同學試試看： rep(x, times = 2)
> 
> --> 怪怪的？是不是應該打成”試”或”鍵入”？

我好像用很多這樣的描述耶，原意是：試試看指令的意思。你是第一個反應這種的同學，所以我先記在腦海裡，不更動。如果有其他同學反應，那我會大修。

## 2

> ```
> 在01-RBasic-02-Data-Structure-Vectors關卡12的時候(不是所有的運算都是向量式的。如果給定一個向量x,max(x)會傳回x中最大的值，而min(x)會傳回x最小的值。有時候在分析的時候，我們如果想要知道數值的範圍，這兩個函數就很有用。請同學寫一個expression來建立一個兩個值的向量，而且第一個值是x的最小值，第二個是x的最大值。)
> ```
> 
> --> 因為我不小心將x給蓋掉，輸入了x <- c(min(x),max(x))，導致我關卡66會出現bug，必須重頭開始闖關

這是swirl的設計問題囉，要改要大修並大測。
又因為我覺得跳出後，再接關，並不會太麻煩，所以目前傾向先放著

## 3

> ```
> 在01-RBasic-04-Factors關卡18
> ```
> 
> --> 正解為grades_factor <- factor(grades, ordered = TRUE, levels = c("C","B","A"))，但是我打grades_factor <- factor(grades, ordered = T, levels = c("C","B","A"))一樣可以跑出正解，只是系統會告訴我不完全正確。

swirl 的 matching 問題，類似2的狀況...
