### ISSUE TITLE
Project-ROpenData-DataTaipei 無法取得資料

### ISSUE THREAD

**Issue by chengu1024** [wush978/DataScienceAndR#270]
| 最後請同學下指令：`df <-
| resourceAquire(rid$resourceId[1])`從資源id中取得youbike的站點資料

> df <- resourceAquire(rid$resourceId[1])
> Error in dataTaipeiCheck(response) : 
> Taipei City Government Open Data Plateform replys the system can't deliver service temporarily.
> Please contact services@mail.taipei.gov.tw if you need further support.
> The accessed url is: http://data.taipei/opendata/datalist/apiAccess?scope=resourceAquire&offset=0&rid=9c6a96d6-353c-41c0-84cc-d181988304f2&format=csv

大大有bug卡關無法繼續：（

**Comment by wush978** [comment]
和這個問題相關：https://github.com/TaipeiRHackers/DataTaipei/issues/48

**Comment by wush978** [comment]
台北市政府對於改善API的建議無回應。

他們的API問題多多，所以我先移除課程了
