### ISSUE TITLE
source("http://wush978.github.io/R/init-swirl.R")有錯誤

### ISSUE THREAD

**Issue by karta282950** [wush978/DataScienceAndR#271]
輸入source("http://wush978.github.io/R/init-swirl.R")後，出現
perl is deprecated. Please use regexp instead
There were 50 or more warnings (use warnings() to see the first 50)
謝謝!

**Comment by wush978** [comment]
請參考：

https://github.com/wush978/DataScienceAndR/wiki/Windows-%E8%A8%AD%E5%AE%9A%E6%8C%87%E5%8D%97#%E5%AE%89%E8%A3%9Dswirl-%E8%AA%B2%E7%A8%8B

**Comment by karta282950** [comment]
Thank you~
TC
