### ISSUE TITLE
RBasic-02-Data-Structure-Vectors 的問題

### ISSUE THREAD

**Issue by hjhsu** [wush978/DataScienceAndR#274]
有些同學會在關卡 12 把 c(min(x), max(x) assign 給 x
swirl 不會檢查出來，但是到了關卡66要 assign 名稱給 x時
無法通過，必須從頭重做才能繼續課程

**Comment by wush978** [comment]
接關應可修正

**Comment by wush978** [comment]
接關應可修正

**Comment by wush978** [comment]
可以幫我確認嗎？

**Comment by hjhsu** [comment]
接關不能修正，值還是會是錯的，基本上會整個卡住，play出去改也不行，得要全部重做才會過。

**Comment by wush978** [comment]
這是swirl的問題
