### ISSUE TITLE
RBasic-03 大魔王中文問題

### ISSUE THREAD

**Issue by hjhsu** [wush978/DataScienceAndR#275]
# ' 請同學找出這個物件的名稱。你的答案只可能是：「character」、「numeric」或「list」

雖然有後面有 character numeric list 這些提示，但是「物件的名稱」這個說法還是容易產生誤會
# ' 請同學找出`pca`的名字

其實應該是要找出 pca 這個 R 物件內含有的各個子物件的名稱

**Comment by unityculture** [comment]
#' 同學找出這個物件的`類型`。你的答案只可能是：「character」、「numeric」或「list」
#' 請同學找出pca這個物件中包含哪些名稱
不知道這樣形容行不行得通？
