### ISSUE TITLE
01-RBasic-07 read.table()參數fileEncoding的說明

### ISSUE THREAD

**Issue by bonzoyang** [wush978/DataScienceAndR#277]
read.table()的參數fileEncoding容易誤導人可以使用read.table(file("檔案路徑"), fileEncoding = "編碼")的方式對file()建立的connection做解碼，但實際上fileEncoding不能對connection做解碼，正確用法應改為read.table("檔案路徑", fileEncoding = "編碼")

**Comment by wush978** [comment]
可以給我一個PR嗎？XDDDD
