### ISSUE TITLE
第三章 list 命名 "coefficient"

### ISSUE THREAD

**Issue by CrystalTu** [wush978/DataScienceAndR#28]
| 另一個我們需要知道的事情，就是list可以有名字。舉例來說，我們除了用`g[[1]]`來取得第一個值之外，也可以用
| `g[["coefficients"]]`來取得第一個值。因為`g`這個向量是有名字的，而第一個名字就是`"coefficients"`。請同學試試看。

改寫成：可以為list命名。

| 適當的使用名字，可以讓程式碼更有可讀性。舉例來說，如果我們知道`g`就是一個迴歸模型，我們也知道迴歸模型通常
| 就是一個參數向量，那我們就會預期：`g[["coefficients"]]`就是這個迴歸模型的參數。（在統計學課本中，迴歸模型的參數
| 通常稱作："coefficients"。

改寫成：適當的命名，可以讓程式碼更易讀
另外應該是所有統計模型的參數都叫做 coefficient 吧 ^^"

**Comment by wush978** [comment]
謝謝，不過因為還沒merge，我就把這個issue轉到PR上囉！
