### ISSUE TITLE
installation problem encountered

### ISSUE THREAD

**Issue by oliahsu** [wush978/DataScienceAndR#307]
試著安裝 swirl
好像有問題 
該怎麼做呢？謝謝!

<img width="540" alt="screen shot 2016-04-11 at 23 36 36" src="https://cloud.githubusercontent.com/assets/18401454/14432807/4f6b96d8-003e-11e6-9f25-9a08330a2abc.png">

**Comment by wush978** [comment]
重新啟動R之後，你先裝套件`digest`，再跑一次快速安裝指令

**Comment by oliahsu** [comment]
問題看來是解決了，謝謝！
