### ISSUE TITLE
UBuntu 安裝說明，增加更多文字提示

### ISSUE THREAD

**Issue by lovelybigdata** [wush978/DataScienceAndR#309]
https://github.com/wush978/DataScienceAndR/wiki/Ubuntu-%E8%A8%AD%E5%AE%9A%E6%8C%87%E5%8D%97

範例：

(1)檢查 ubuntu 版本指令：
 lsb_release  -a
例如，執行後結果如下：
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
可知 codename 為 trusty

編輯 /etc/apt/sources.list (例：vim /etc/apt/sources.list  ) 並且新增
deb http://cran.csie.ntu.edu.tw/bin/linux/ubuntu  trusty/ 
注意：/ubuntu  trusty/    中間有一個空白

然後再執行
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
sudo apt-get update
sudo apt-get install -y r-base libcurl4-openssl-dev libxml2-dev

2016/4/18 時會更新至 3.2.5

**Comment by wush978** [comment]
你直接改Wiki吧！

Wiki的定義就是所有人都可以改的文件...
