### ISSUE TITLE
無法開啟swirl

### ISSUE THREAD

**Issue by tsaiweiche** [wush978/DataScienceAndR#316]
執行：source("http://wush978.github.io/R/init-swirl.R")之後，出現

> perlis deprecated. Please use regexp instead
> Warning message:
> package ‘curl’ was built under R version 3.2.5 
> 
> 我繼續輸入
> library(swirl)
> swirl()
> 出現
> 
> Error in match.arg(type, c("success", "failure", "error", "skip", "warning")) : 
>   'arg' must be NULL or a character vector| Leaving swirl now. Type swirl() to resume.
> 
> google建議的方式都無法解決，請問該怎麼辦，謝謝

**Comment by wush978** [comment]
> perlis deprecated. Please use regexp instead
> Warning message:
> package 『curl' was built under R version 3.2.5

上述訊息不影響安裝

> Error in match.arg(type, c("success", "failure", "error", "skip", "warning")) : 
> 'arg' must be NULL or a character vector| Leaving swirl now. Type swirl() to resume.

目前我還不知道導致這類錯度的理由。

不過有朋有回報說，將其它套件移除後重新安裝即可恢復正常

**Comment by tsaiweiche** [comment]
謝謝你的回覆，請問是將其他那些套件移除？是所有套件嗎？

**Comment by wush978** [comment]
根據：https://gitter.im/wush978/DataScienceAndR?at=57240821e10a59c06107502d
試試移除RCurl, testthat, crayon再重裝swirl
