### ISSUE TITLE
nycflights13 v0.2 會影響答案結果

### ISSUE THREAD

**Issue by wush978** [wush978/DataScienceAndR#319]
1. 限定nycflights13 的套件必須為 v0.1
2. 在 wush978.github.io/R 底下佈署 nycflights13 v0.1的套件

**Comment by hjhsu** [comment]
雖然有指定要灌 nycflights13 v0.1 但是目前看起來好像還是會灌 v0.2版, 這個問題要先用臨時性的解法來解決嗎?

**Comment by wush978** [comment]
從我的repo安裝呢？

**Comment by hjhsu** [comment]
> install.packages("nycflights13", repos = "http://wush978.github.io/R")

  There is a binary version available but the source version is later:
             binary source needs_compilation
nycflights13    0.1  0.2.0             FALSE

installing the source package ‘nycflights13’

trying URL 'http://wush978.github.io/R/src/contrib/nycflights13_0.2.0.tar.gz'

**Comment by hjhsu** [comment]
從你的 repos 指定要灌 binary 版本的，可以灌到 0.1 版，但好像不是長久之計......lol

> install.packages("nycflights13", repos = "http://wush978.github.io/R", type="binary")

  There is a binary version available (and will be installed) but the source version
  is later:
             binary source
nycflights13    0.1  0.2.0

trying URL 'http://wush978.github.io/R/bin/windows/contrib/3.3/nycflights13_0.1.zip'

**Comment by wush978** [comment]
OK

**Comment by hjhsu** [comment]
上面這個解法會有點問題，你 repository 裡面的 binary 檔，沒辦法用在 R 3.30 以上的版本......

**Comment by wush978** [comment]
branch latest以後會持續追蹤新版套件的相容性
