### ISSUE TITLE
 Project-ROpenData-Power-GDP 的第一個作業的可能的錯誤

### ISSUE THREAD

**Issue by wush978** [wush978/DataScienceAndR#321]
單元21, Project-ROpenData-Power-GDP 的第一個作業。
[## 我們拿下一個開始的index - 1 當成現在結尾的index
year.index.end <- c(tail(year.index, -1), length(gdp.split))
]
tail裡，應是 ”year.index-1“

**Comment by crikyre** [comment]
我執行關卡22的時候，會出現錯誤~重啟程式，
要怎麼解決呢

**Comment by wush978** [comment]
我弄錯了，這裡這樣寫沒錯

但是仍然修正一下說明文字
