### ISSUE TITLE
Wiki - Mac OS X 設定指南中的R3.2.3載點失效

### ISSUE THREAD

**Issue by unityculture** [wush978/DataScienceAndR#322]
Wush 大你好！
[Wiki - Mac OS X 設定指南中](https://github.com/wush978/DataScienceAndR/wiki/Mac-OS-X-%E8%A8%AD%E5%AE%9A%E6%8C%87%E5%8D%97) 的 R 3.2.3 載點似乎失效！

**Comment by wush978** [comment]
噢，如果是wiki的話，那每個人都可以修改喔
