### ISSUE TITLE
RDataEngineer-06-join 關卡 43, 44

### ISSUE THREAD

**Issue by hjhsu** [wush978/DataScienceAndR#329]
在這兩個關卡 View 指令會被執行兩次，應該是因為對答案的時候又執行了一次。

**Comment by wush978** [comment]
感謝回報，不過目前架構要修改很困難...

**Comment by crikyre** [comment]
關卡38 我照答案貼上還是錯~~ 求助
Error : nrow(answer02.1) == 116774 is not TRUE
另外為什麼不能skip() 過去呢？

**Comment by MitsunChieh** [comment]
好像不只這兩個，之前也有發生過
至少有 RDataEngineer-06-join: step 34（其他沒有記錄）

**Comment by wush978** [comment]
@MitsunChieh 請問是View兩次的問題嘛?

**Comment by MitsunChieh** [comment]
是 View 兩次的問題。

**Comment by wush978** [comment]
了解
