### ISSUE TITLE
Association Rules bug

### ISSUE THREAD

**Issue by clariceliu** [wush978/DataScienceAndR#330]
Association Rules課程:
"這條規則就有歸納出lhs（因）和rhs（果）的關係。也就是說，擁有一個Full-time的工作的人，資產上通常不會有損失。 support 0.56代表的是，同時有lhs + rhs 特性的人，占總資料 的56% 。"
應該是"support 0.56代表的是，有lhs特性的人，占總資料 的56% 。"吧?

**Comment by wush978** [comment]
DataScienceAndR系列並不包含Data Mining的課程喔！
