### ISSUE TITLE
下載swirl套件，出現下列訊息，不能進入 [00-Hello-DataScienceAndR]課程

### ISSUE THREAD

**Issue by aven0524** [wush978/DataScienceAndR#333]
| Hi! Type swirl() when you are ready to begin.

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Peer certificate cannot be authenticated with given CA certificates

**Comment by aven0524** [comment]
不能進入 [00-Hello-DataScienceAndR]課程
| To begin, you must install a course. I can install a course for you from the internet, or
| I can send you to a web page (https://github.com/swirldev/swirl_courses) which will
| provide course options and directions for installing courses yourself. (If you are not
| connected to the internet, type 0 to exit.)

1: R Programming: The basics of programming in R
2: Regression Models: The basics of regression modeling in R
3: Statistical Inference: The basics of statistical inference in R
4: Exploratory Data Analysis: The basics of exploring data in R
5: Don't install anything for me. I'll do it myself.

Selection: 1
  |===================================================================================| 100%

| Course installed successfully!

| Please choose a course, or type 0 to exit swirl.

1: R Programming
2: Take me to the swirl course repository!

Selection: 1

| Please choose a lesson, or type 0 to return to course menu.

 1: Basic Building Blocks      2: Workspace and Files        3: Sequences of Numbers  
 4: Vectors                    5: Missing Values             6: Subsetting Vectors  
 7: Matrices and Data Frames   8: Logic                      9: Functions  
10: lapply and sapply         11: vapply and tapply         12: Looking at Data  
13: Simulation                14: Dates and Times           15: Base Graphics

**Comment by wush978** [comment]
你應該是安裝失敗了。
請重開R後再執行：`source("http://wush978.github.io/R/init-swirl.R")`一次

**Comment by wush978** [comment]
如果有錯誤，歡迎再re-open issue
