### ISSUE TITLE
安裝必要之Swirl套件時，出現錯誤訊息無法進行下一步

### ISSUE THREAD

**Issue by chuyenyang** [wush978/DataScienceAndR#334]
請問我在執行自動安裝程式後會出現
curl: (22) The requested URL returned error: 404
Warning in install.packages :
  download had nonzero exit status
Warning in install.packages :
  無法開啟壓縮過的檔案 '/var/folders/z8/z8LdmDVOHhCTJUqOx8BpPk+++TI/-Tmp-//RtmpxEcnTi/file6b15968ed24'，可能的原因是 'No such file or directory'

而無法進行後續安裝，該如何解決？
謝謝協助～

**Comment by wush978** [comment]
Hi @chuyenyang 
能不能麻煩你再試一次看看呢？
有可能是網路問題

**Comment by chuyenyang** [comment]
Hi wush大

謝謝你的回覆！
我換了一個網路環境重新嘗試，但還是出現一樣的狀況。
您所謂的網路問題，是指網域問題還是網路連線狀況呢？

謝謝你的協助耶～

**Comment by wush978** [comment]
原因是你的錯誤訊息：`download had nonzero exit status` 代表下載失敗

可能的理由很多，網路只是最普遍的理由之一。
我列一些我想到的：
- 你的網址有沒有打錯呢？(錯誤訊息404可能的原因是網址錯誤)
- 你方便Po你在R跑`sessionInfo()`的結果給我嗎？
- 你要確定你的網路，是一般的網路。有些公司的網路會擋著特定的port，導致下載失敗呢？
