### ISSUE TITLE
安裝 Swirl 出現 Error in curl

### ISSUE THREAD

**Issue by JianChengChang** [wush978/DataScienceAndR#335]
Wush大大您好 ...

R版本 3.3.1
我在安裝Swirl時

自動
source("http://wush978.github.io/R/init-swirl.R")

手動
repos <- "http://wush978.github.io/R"
utils::install.packages("swirl", repos = repos, type = "source")
library(swirl)
library(curl)
try(uninstall_course("DataScienceAndR"), silent=TRUE)
install_course_github("wush978", "DataScienceAndR", "course")

都會出現
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

然後無法進入到
| Would you like to continue with one of these lessons?
1:  DataScienceAndR Rbasic-01-Introduction
2:  No. Let me start something new.

已經試過
1. 關閉R，重新安裝Swirl
2. 重新安裝R
均無效 ....

請問Wush大大 還有什麼方法可解決此問題嗎 ~?

**Comment by wush978** [comment]
Hi @JianChengChang 
我也懷疑你跟 #334 一樣，是網路問題

**Comment by JianChengChang** [comment]
Dear @wush978 
好的，那我晚一點換個網路環境試試看 ...
