### ISSUE TITLE
安裝Swirl出現錯誤無法執行下一步

### ISSUE THREAD

**Issue by jujulai** [wush978/DataScienceAndR#336]
**hello Wush : )
OS Win10下載完成R 3.3.1後
打開R ，執行：source("http://wush978.github.io/R/init-swirl.R")
出現以下訊息:**

The downloaded binary packages are in
        C:\Users\James Lai\AppData\Local\Temp\Rtmp2ZFH82\downloaded_packages
installing the source package ‘swirl’

嘗試 URL 'http://wush978.github.io/R/src/contrib/swirl_101.3.1-7.tar.gz'
Content type 'application/octet-stream' length 95867 bytes (93 KB)
downloaded 93 KB

'D:\Judy' 不是內部或外部命令、可執行的程式或批次檔。

The downloaded source packages are in
        ‘C:\Users\James Lai\AppData\Local\Temp\Rtmp2ZFH82\downloaded_packages’
Error in library(swirl) : there is no package called ‘swirl’
此外: Warning messages:
1: 執行中命令 '"D:/Judy Lai/learn/R-3.3.1/bin/x64/R" CMD INSTALL -l "D:\Judy Lai\learn\R-3.3.1\library" C:\Users\JAMESL~1\AppData\Local\Temp\Rtmp2ZFH82/downloaded_packages/swirl_101.3.1-7.tar.gz' 已有狀態 1 
2: In utils::install.packages("swirl", repos = "http://wush978.github.io/R") :
  installation of package ‘swirl’ had non-zero exit status

**重新下載軟體並重開機再次執行也是發生一樣的狀況,網路為一般社區網路,
請教您有什麼辦法可以讓她順利執行呢?謝謝！: )**

**Comment by wush978** [comment]
你的使用者名稱是不是有空白呢？

**Comment by jujulai** [comment]
是的,將電腦使用者名稱取消空白鍵之後就可以順利執行安裝與課程了!
謝謝Wush!
請問這是因為程式遇到空白會辨認不到的關係嗎?

**Comment by wush978** [comment]
應該和路徑的處理有關。
