### ISSUE TITLE
載swirl()的課程，均出現英文的解說且未顯示00-Hello-DataScienceAndR等課程

### ISSUE THREAD

**Issue by aven0524** [wush978/DataScienceAndR#338]
The downloaded source packages are in
      ‘C:\Users\hb11082\AppData\Local\Temp\RtmpY78DUA\downloaded_packages’
Error in curl::curl_fetch_memory(url, handle = handle) : 

  Peer certificate cannot be authenticated with given CA certificates

> swirl()

| Welcome to swirl! Please sign in. If you've been here before, use the same name as you did
| then. If you are new, call yourself something unique.

What shall I call you? a

| Thanks, a. Let's cover a couple of quick housekeeping items before we begin our first
| lesson. First of all, you should know that when you see '...', that means you should press
| Enter when you are done reading and ready to continue.

...  <-- That's your cue to press Enter to continue

| Also, when you see 'ANSWER:', the R prompt (>), or when you are asked to select from a
| list, that means it's your turn to enter a response, then press Enter to continue.

Select 1, 2, or 3 and press Enter 

1: Continue.
2: Proceed.
3: Let's get going!

Selection: 1

| You can exit swirl and return to the R prompt (>) at any time by pressing the Esc key. If
| you are already at the prompt, type bye() to exit and save your progress. When you exit
| properly, you'll see a short message letting you know you've done so.

| When you are at the R prompt (>):
| -- Typing skip() allows you to skip the current question.
| -- Typing play() lets you experiment with R on your own; swirl will ignore what you do...
| -- UNTIL you type nxt() which will regain swirl's attention.
| -- Typing bye() causes swirl to exit. Your progress will be saved.
| -- Typing main() returns you to swirl's main menu.
| -- Typing info() displays these options again.

| Let's get started!

...

| To begin, you must install a course. I can install a course for you from the internet, or
| I can send you to a web page (https://github.com/swirldev/swirl_courses) which will
| provide course options and directions for installing courses yourself. (If you are not
| connected to the internet, type 0 to exit.)

1: R Programming: The basics of programming in R
2: Regression Models: The basics of regression modeling in R
3: Statistical Inference: The basics of statistical inference in R
4: Exploratory Data Analysis: The basics of exploring data in R
5: Don't install anything for me. I'll do it myself.

沒有顯示為00-Hello-DataScienceAndR等課程系列，煩請老師協助
謝謝

**Comment by wush978** [comment]
請重開R後依照網站指示安裝課程
過程中如有error message 請附上

**Comment by aven0524** [comment]
error message 如下，無法顯示到00-Hello-DataScienceAndR

| Hi! Type swirl() when you are ready to begin.

**

> Error in curl::curl_fetch_memory(url, handle = handle) : 
>   Peer certificate cannot be authenticated with given CA certificates

**
