### ISSUE TITLE
Bug in final section of 21:Project-ROpenData-Power-GDP?

### ISSUE THREAD

**Issue by wyharveychen** [wush978/DataScienceAndR#347]
在最後的power-gdp.R的部分中
官方解答表示要
power.df3 <-
  power.df2 %>%
  mutate(id2 = translation.gdp[id]) 
然而此處是否應為 mutate(id2 = translation.power[id]) ? 如此才能對應到正確的編號

(不過submit時如果不這樣子照著他打又不會過...)

**Comment by wush978** [comment]
感謝回報，我再檢查看看

**Comment by wush978** [comment]
已經修正，感謝
