### ISSUE TITLE
00-Hello-DataScienceAndR - lesson.src.yaml - 中文字義確認

### ISSUE THREAD

**Issue by tingtingyeh** [wush978/DataScienceAndR#355]
第17、18行寫到:  
    本課程的目的是為了測試同學的環境是否正常，能否進行本教材。
    完成測試之後，我們會跟同學說明本教材的一些功能。

這裡的"一些"是有意義的嗎?
完成測試之後是會一併說明所有教材的功能，還是只會先跟同學說教材的部分功能呢?

**Comment by wush978** [comment]
我認為寫「部份功能」比較保險，因為功能會一直變化...
