### ISSUE TITLE
00-Hello-DataScienceAndR Step 7

### ISSUE THREAD

**Issue by hjhsu** [wush978/DataScienceAndR#360]
|=======================================                                       |  50% (step: 7/13)

| 請確認Rstudio是否開啟名稱為「test-script.R」的檔案，並且已經顯示：「#
| 這是測試功能的檔案」等字眼。 如果無法看到中文，請依序點選Rstudio左上角的File -> Reopen With
| Encoding... -> 選取：UTF-8。
| 使用Windows的同學，如果打開的檔案後無法看到文字，請改由使用非中文的使用者帳號進行課程。
| （針對此問題，目前尚沒有更好的解決方法，麻煩遇到此問題的同學切換帳號後，繼續進行課程）

我印象中這邊應該是會要求同學輸入 submit()
但是現在題目的描述要求同學輸入 submit() 的字眼不見了......

**Comment by wush978** [comment]
https://github.com/wush978/DataScienceAndR/blob/course/00-Hello-DataScienceAndR/scripts/test-script.R

打開的script檔案中會有`submit`喔!
