### ISSUE TITLE
01-RBasic-03-Data-Structure-Object 錯字回報

### ISSUE THREAD

**Issue by tzuchenkuo** [wush978/DataScienceAndR#361]
#進度86%處
| 另一個值得注意到的是`paste`在串接字串時，在字串中間會留下一個預留的空格。
| 如果不希望**再自船**間出現空格，可以改為使用`paste0`。　  
→在字串

另外Wush 我是修台大 CS+UX 的 R 在做這回的隨堂練習時，發現即便答案跟解答一樣，仍舊無法submit()
有截圖，課堂上再請教您 希望不用被扣分T____T

**Comment by wush978** [comment]
感謝回報

**Comment by tzuchenkuo** [comment]
01-RBasic-05-Arrays-Matrices
#進度87% (step: 56/64)

| 在R 中，線性代數運算的底層是透過BLAS等函式庫做運算的，所以效能遠勝過自己用C 寫的線性代數運算。 另外，R 預設的BLAS庫為比較被廣泛驗證過正確性的，而非效能比較快，「但是還比較年輕的BLAS函式庫，例如OpenBLAS。」#這具有點不是很明白要傳達的意思
| 這是因為，R core Team認為正確性比較重要，所以目前是採用比較舊，但是也比較可靠的BLAS庫。

**Comment by wush978** [comment]
這段話只是說明R 預設的BLAS庫為比較被廣泛驗證過正確性的版本，而非效能比較快版本。

我把原本不通順的敘述做了調整。
