### ISSUE TITLE
安裝DataScienceAndR 00-Hello-DataScienceAndR問題

### ISSUE THREAD

**Issue by yufenwang82** [wush978/DataScienceAndR#377]
我試著按照教學安裝多次都會卡住，Console顯示如下：

 (step: 6/13)

| <U+8ACB><U+5728>console<U+4E2D><U+8F38><U+5165>:`chat()`<U+3002><U+6B64><U+90E8><U+5206><U+5FC5><U+9700><U+8981><U+8F38><U+5165><U+8207><U+4E0A><U+8FF0><U+4E00><U+6A23><U+7684><U+6307><U+4EE4><U+624D><U+6703><U+904E><U+95DC><U+3002>
| <U+9019><U+500B><U+6307><U+4EE4><U+80FD><U+6253><U+958B><U+804A><U+5929><U+5BA4><U+7684><U+7DB2><U+9801><U+3002><U+8A3B><U+518A>github<U+5E33><U+6236>(<https://github.com/join>)<U+4E4B><U+5F8C>,<U+5373><U+53EF><U+5728><U+9019><U+500B><U+804A><U+5929><U+5BA4><U+4E4B><U+4E2D><U+6C42><U+52A9><U+3002>

請問我該如何解決？
謝謝！
Andrea

**Comment by wush978** [comment]
能不能麻煩你輸入`sessionInfo()`後把結果貼上來？

**Comment by yufenwang82** [comment]
我解決了
謝謝！

**Comment by wush978** [comment]
恭喜
