### ISSUE TITLE
安裝說明與安裝程式附上R的版本限制與自動檢查

### ISSUE THREAD

**Issue by wush978** [wush978/DataScienceAndR#379]

**Comment by HuangYuShan** [comment]
老師，我在安裝swirl時出現了一下的狀況，請問下一步我該怎麼做呢?
> source("http://wush978.github.io/R/init-swirl.R")
Loading required package: remotes
Loading required package: pvm
Installing stringi (1.0-1) ...
Install stringi (1.0-1) from MRAN snapshot of date 2016-05-28 for type: win.binary
Installing stringr (1.0.0) ...
Install stringr (1.0.0) from MRAN snapshot of date 2016-08-20 for type: win.binary
Installing package into ‘C:/Users/user/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)

  There is a binary version available (and will be installed) but
  the source version is later:
        binary source
stringi  1.0-1  1.1.1

trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-05-28/bin/windows/contrib/3.3/stringi_1.0-1.zip'
Content type 'application/zip' length 14302873 bytes (13.6 MB)
downloaded 13.6 MB

package ‘stringi’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘stringi’

The downloaded binary packages are in
	C:\Users\user\AppData\Local\Temp\Rtmp4kga6E\downloaded_packages
Installing package into ‘C:/Users/user/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)

  There is a binary version available (and will be installed) but
  the source version is later:
        binary source
stringr  1.0.0  1.1.0

Warning: package ‘stringr’ is in use and will not be installed
Installing package into ‘C:/Users/user/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependency ‘stringi’

trying URL 'https://wush978.github.io/R/bin/windows/contrib/3.3/stringi_1.0-1.zip'
Content type 'application/zip' length 14266306 bytes (13.6 MB)
downloaded 13.6 MB

package ‘stringi’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘stringi’

The downloaded binary packages are in
	C:\Users\user\AppData\Local\Temp\Rtmp4kga6E\downloaded_packages
installing the source package ‘swirl’

trying URL 'https://wush978.github.io/R/src/contrib/swirl_101.5.4.4.tar.gz'
Content type 'application/octet-stream' length 109271 bytes (106 KB)
downloaded 106 KB

ERROR: dependency 'stringi' is not available for package 'swirl'
* removing 'C:/Users/user/Documents/R/win-library/3.3/swirl'

The downloaded source packages are in
	‘C:\Users\user\AppData\Local\Temp\Rtmp4kga6E\downloaded_packages’
Error in library(swirl) : there is no package called ‘swirl’
In addition: Warning messages:
1: running command '"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" CMD INSTALL -l "C:\Users\user\Documents\R\win-library\3.3" C:\Users\user\AppData\Local\Temp\Rtmp4kga6E/downloaded_packages/swirl_101.5.4.4.tar.gz' had status 1 
2: In utils::install.packages("swirl", repos = repos) :
  installation of package ‘swirl’ had non-zero exit status

**Comment by wush978** [comment]
麻煩你先移除stringi套件之後，重開R，再跑一次 `source("http://wush978.github.io/R/init-swirl.R")`

參考指令:

`remove.packages("stringi")`

**Comment by chao0323** [comment]
老師您好，我安裝出現問題請問該如何排除呢
> source("http://wush978.github.io/R/init-swirl.R")
Loading required package: remotes
Loading required package: pvm
Downloading GitHub repo wush978/pvm@dcbcb71f529e805493058732b70505759a8f0501
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot download all files
In addition: Warning messages:
1: package ‘remotes’ was built under R version 3.3.3 
2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘pvm’

**Comment by wush978** [comment]
@chao0323 
麻煩你重開R，確認網路環境之後再跑一次看看喔！

我看到錯誤的原因是：下載pvm套件失敗

**Comment by chao0323** [comment]
請問有別總方法安裝  pvm套件嗎?我換了兩個網路環境都還是連不上去，另外也有devtools安裝也出錯
devtools::install_github('wush978/pvm@master')
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't connect to server

**Comment by wush978** [comment]
@chao0323 

我在想可能的原因是你的網路限制。
舉例來說，上述的方法在公司設定防火牆，只讓員工做一般網路使用後，很容易失效。

我剛剛改了安裝的script內容。麻煩你試試看有沒有解決你的問題。

**Comment by chao0323** [comment]
老師您好，看起來好像有多跑了一下，看結果好像還是失敗?
> source("http://wush978.github.io/R/init-swirl.R")
Loading required package: pvm
trying URL 'https://wush978.github.io/R/src/contrib/pvm_0.2.3.tar.gz'
Content type 'application/octet-stream' length 829537 bytes (810 KB)
downloaded 810 KB

* installing *source* package 'pvm' ...
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (pvm)

The downloaded source packages are in
	‘C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages’
Installing rstudioapi (0.5) ...
Install rstudioapi (0.5) from MRAN snapshot of date 2016-06-30 for type: win.binary
Installing openssl (0.9.2) ...
Install openssl (0.9.2) from MRAN snapshot of date 2016-05-23 for type: win.binary
Installing getPass (0.1-1) ...
Install getPass (0.1-1) from CRAN
Installing digest (0.6.9) ...
Install digest (0.6.9) from MRAN snapshot of date 2016-08-03 for type: win.binary
Installing curl (0.9.6) ...
Install curl (0.9.6) from MRAN snapshot of date 2016-04-11 for type: win.binary
Installing R6 (2.1.2) ...
Install R6 (2.1.2) from MRAN snapshot of date 2016-08-20 for type: win.binary
Installing mime (0.4) ...
Install mime (0.4) from MRAN snapshot of date 2016-07-08 for type: win.binary
Installing stringi (1.0-1) ...
Install stringi (1.0-1) from MRAN snapshot of date 2016-05-28 for type: win.binary
Installing Rcpp (0.12.4) ...
Install Rcpp (0.12.4) from MRAN snapshot of date 2016-05-23 for type: win.binary
Installing jsonlite (0.9.19) ...
Install jsonlite (0.9.19) from MRAN snapshot of date 2016-05-23 for type: win.binary
Installing stringr (1.0.0) ...
Install stringr (1.0.0) from MRAN snapshot of date 2016-08-20 for type: win.binary
Installing rappdirs (0.3.1) ...
Install rappdirs (0.3.1) from CRAN
Installing crayon (1.3.1) ...
Install crayon (1.3.1) from MRAN snapshot of date 2016-06-30 for type: win.binary
Installing testthat (0.11.0) ...
Install testthat (0.11.0) from MRAN snapshot of date 2016-04-22 for type: win.binary
Installing httr (1.1.0) ...
Install httr (1.1.0) from MRAN snapshot of date 2016-06-15 for type: win.binary
Installing httpuv (1.3.3) ...
Install httpuv (1.3.3) from CRAN

  There is a binary version available (and will be installed) but the
  source version is later:
           binary source
rstudioapi    0.5    0.6

trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-06-30/bin/windows/contrib/3.3/rstudioapi_0.5.zip'
Content type 'application/zip' length 46188 bytes (45 KB)
downloaded 45 KB

package ‘rstudioapi’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages
trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-05-23/bin/windows/contrib/3.3/openssl_0.9.2.zip'
Content type 'application/zip' length 2713098 bytes (2.6 MB)
downloaded 2.6 MB

package ‘openssl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/getPass_0.1-1.zip'
Content type 'application/zip' length 249835 bytes (243 KB)
downloaded 243 KB

package ‘getPass’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages

  There is a binary version available (and will be installed) but the
  source version is later:
       binary source
digest  0.6.9 0.6.10

trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-08-03/bin/windows/contrib/3.3/digest_0.6.9.zip'
Content type 'application/zip' length 167369 bytes (163 KB)
downloaded 163 KB

package ‘digest’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘digest’

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages

  There is a binary version available (and will be installed) but the
  source version is later:
     binary source
curl  0.9.6  0.9.7

trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-04-11/bin/windows/contrib/3.3/curl_0.9.6.zip'
Content type 'application/zip' length 4403946 bytes (4.2 MB)
downloaded 4.2 MB

package ‘curl’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘curl’

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages

  There is a binary version available (and will be installed) but the
  source version is later:
   binary source
R6  2.1.2  2.1.3

trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-08-20/bin/windows/contrib/3.3/R6_2.1.2.zip'
Content type 'application/zip' length 271202 bytes (264 KB)
downloaded 264 KB

package ‘R6’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages

  There is a binary version available (and will be installed) but the
  source version is later:
     binary source
mime    0.4    0.5

trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-07-08/bin/windows/contrib/3.3/mime_0.4.zip'
Content type 'application/zip' length 37402 bytes (36 KB)
downloaded 36 KB

package ‘mime’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages

  There is a binary version available (and will be installed) but the
  source version is later:
        binary source
stringi  1.0-1  1.1.1

trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-05-28/bin/windows/contrib/3.3/stringi_1.0-1.zip'
Content type 'application/zip' length 14302873 bytes (13.6 MB)
downloaded 13.6 MB

package ‘stringi’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages
trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-05-23/bin/windows/contrib/3.3/Rcpp_0.12.4.zip'
Content type 'application/zip' length 3249215 bytes (3.1 MB)
downloaded 3.1 MB

package ‘Rcpp’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages
trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-05-23/bin/windows/contrib/3.3/jsonlite_0.9.19.zip'
Content type 'application/zip' length 1006920 bytes (983 KB)
downloaded 983 KB

package ‘jsonlite’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages

  There is a binary version available (and will be installed) but the
  source version is later:
        binary source
stringr  1.0.0  1.1.0

trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-08-20/bin/windows/contrib/3.3/stringr_1.0.0.zip'
Content type 'application/zip' length 82940 bytes (80 KB)
downloaded 80 KB

package ‘stringr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/rappdirs_0.3.1.zip'
Content type 'application/zip' length 79687 bytes (77 KB)
downloaded 77 KB

package ‘rappdirs’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages

  There is a binary version available (and will be installed) but the
  source version is later:
       binary source
crayon  1.3.1  1.3.2

trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-06-30/bin/windows/contrib/3.3/crayon_1.3.1.zip'
Content type 'application/zip' length 606351 bytes (592 KB)
downloaded 592 KB

package ‘crayon’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages

  There is a binary version available (and will be installed) but the
  source version is later:
         binary source
testthat 0.11.0  1.0.1

trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-04-22/bin/windows/contrib/3.3/testthat_0.11.0.zip'
Content type 'application/zip' length 263537 bytes (257 KB)
downloaded 257 KB

package ‘testthat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages

  There is a binary version available (and will be installed) but the
  source version is later:
     binary source
httr  1.1.0  1.2.0

trying URL 'https://mran.revolutionanalytics.com/snapshot/2016-06-15/bin/windows/contrib/3.3/httr_1.1.0.zip'
Content type 'application/zip' length 262776 bytes (256 KB)
downloaded 256 KB

package ‘httr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/httpuv_1.3.3.zip'
Content type 'application/zip' length 917008 bytes (895 KB)
downloaded 895 KB

package ‘httpuv’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages
also installing the dependency ‘digest’

trying URL 'https://wush978.github.io/R/bin/windows/contrib/3.3/digest_0.6.9.zip'
Content type 'application/zip' length 171676 bytes (167 KB)
downloaded 167 KB

package ‘digest’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘digest’

The downloaded binary packages are in
	C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages
installing the source package ‘swirl’

trying URL 'https://wush978.github.io/R/src/contrib/swirl_101.5.4.4.tar.gz'
Content type 'application/octet-stream' length 109367 bytes (106 KB)
downloaded 106 KB

ERROR: dependency 'digest' is not available for package 'swirl'
* removing 'C:/Program Files/R/R-3.3.1/library/swirl'

The downloaded source packages are in
	‘C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3\downloaded_packages’
Error in library(swirl) : there is no package called ‘swirl’
In addition: Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘pvm’
2: running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "C:\Program Files\R\R-3.3.1\library" C:\Users\A97833\AppData\Local\Temp\RtmpqEkwY3/downloaded_packages/swirl_101.5.4.4.tar.gz' had status 1 
3: In utils::install.packages("swirl", repos = repos) :
  installation of package ‘swirl’ had non-zero exit status
>

**Comment by wush978** [comment]
@chao0323 

我看到digest套件安裝失敗。可能的原因是你正在使用。
所以建議你重開R之後再試一次看看。

**Comment by chao0323** [comment]
非常謝謝老師的幫忙問題已排解，另外登入因公司限制無法登入google與fb無法登入，請問如何申請Classroom帳密? 另附上個人信箱(j0913901778@gmail.com)  謝謝您

**Comment by wush978** [comment]
那是付費的服務耶。只能麻煩你使用自己的3g/4g網路或是請網管通融了。不好意思。

**Comment by feanneb** [comment]
老師你好，我安裝出現以下問題，不知道怎麼解決，求解，謝謝。

R version 3.4.2 (2017-09-28) -- "Short Summer"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> source("http://wush978.github.io/R/init-swirl.R")
Loading required package: remotes
Loading required package: pvm
trying URL 'https://wush978.github.io/R/src/contrib/pvm_0.2.4.tar.gz'
Content type 'application/gzip' length 829629 bytes (810 KB)
downloaded 810 KB

'D:\Program' is not recognized as an internal or external command,
operable program or batch file.

The downloaded source packages are in
	‘C:\Users\ftwy\AppData\Local\Temp\RtmpYxNkSL\downloaded_packages’
Error in loadNamespace(name) : there is no package called ‘pvm’
In addition: Warning messages:
1: running command '"D:/Program Files/R-3.4.2/bin/x64/R" CMD INSTALL -l "D:\Program Files\R-3.4.2\library" C:\Users\ftwy\AppData\Local\Temp\RtmpYxNkSL/downloaded_packages/pvm_0.2.4.tar.gz' had status 1 
2: In utils::install.packages("pvm", repos = "https://wush978.github.io/R",  :
  installation of package ‘pvm’ had non-zero exit status
>

**Comment by wush978** [comment]
建議重新安裝R到`D:\R\R-3.4.2`，不要裝到Program Files底下

**Comment by wush978** [comment]
在開啟Rstudio的時候如果按著`CTRL`不放，可以選擇底層R的位置
