### ISSUE TITLE
01-RBasic-06-List-DataFrame, mode練習打錯指令仍可過關

### ISSUE THREAD

**Issue by JohnsonHsieh** [wush978/DataScienceAndR#385]
![image](https://user-images.githubusercontent.com/1272783/26956182-762b9a7c-4cee-11e7-94cf-d95403a3c2e7.png)

01-RBasic-06-List-DataFrame, 裡面好像有一題有問題，我應該是打錯指令（應該是 mode(x[[3]])而不是 attributes(x[[3]])），但是系統還是判斷我回答正確？

**Comment by wush978** [comment]
這應該是一個嚴重的問題： 如果只用`omnitest(correctVal = ...)`作檢查，所有`NULL`都過pass

**Comment by wush978** [comment]
改用`val_is`應該可以解決單一的問題

但可能有其他的問題，得想個辦法寫程式檢查

**Comment by wush978** [comment]
在這個issue中，改成`val_is`確實解決了問題
這裡列出所有的問題： #399
