### ISSUE TITLE
答案錯誤

### ISSUE THREAD

**Issue by Ray0907** [wush978/DataScienceAndR#386]
如題，答案就算參考解答寫出來，也是顯示不對。
![2017-06-15 8 33 33](https://user-images.githubusercontent.com/29456968/27181478-5768894e-520a-11e7-80be-a7532f5a62dc.png)

**Comment by wush978** [comment]
根據錯誤訊息，應該是沒存檔，或是寫錯檔案的關係

**Comment by Ray0907** [comment]
那請問要怎麼處理呢？ 謝謝！

**Comment by wush978** [comment]
存檔或是編輯正確的檔案。

進入大魔王關卡的時候，會開啟一個新的檔案，那才是翻轉教室會檢查的檔案（每次重開R會不一樣）。寫完之後請存檔後再到console輸入`submit()`。
