### ISSUE TITLE
01-RBasic最後作答的第一題就卡關了

### ISSUE THREAD

**Issue by RadientTang** [wush978/DataScienceAndR#394]
# 社會服務業自民國87至民國91年的年度用電量（度）
year1 <- 87:91
power1 <- c(6097059332, 6425887925, 6982579022, 7323992602.53436, 7954239517) 
# 製造業自民國87至民國91年的年度用電量（度）
power2 <- c(59090445718, 61981666330, 67378329131, 66127460204.6482, 69696372914.6949) 

# 請選出年度(`year1`)中，社會服務業用電量超過`7e9` 的年份。
# （`7e9`是R 的科學符號，代表`7 * 10^9`）

year1.answer1 <- {year1 <- power1 & power1 > 7e9}

不知道為何這樣寫不行?  不好意思我新手

**Comment by wush978** [comment]
要用中括號做喔

**Comment by RadientTang** [comment]
後來想半天，year1[power1 >7e9]
從year1的序列裡，抓出跟power1中數據大於7e9一樣的位置，因為年份是線性排列，所以可以用這個方式。
我原本的方式就會在大於7e9的年份變成Ture

**Comment by wush978** [comment]
👍
