### ISSUE TITLE
RVisualization02MultipleVariablesVisualization : plot參數

### ISSUE THREAD

**Issue by jialinhuang00** [wush978/DataScienceAndR#396]
[變數](https://github.com/Jiaaa1014/R-/blob/master/images/RVisualization02ggplot2-variables.png)

> (step: 44/56)
> 繪圖函數`plot`也可以使用`formula`進行繪圖。 
請同學在`plot`函數中的第一個參數使用`read ~math`，第二個參數使用`data=hsb`，重新繪製學生數學與閱讀成績的散佈圖。 請注意波浪符號`~`左邊的參數代表反應變數
 (response variable)；而右邊的參數代表`解釋變數 (dependent variable)`。

右邊的參數應該是independent。

**Comment by wush978** [comment]
是的，這是一個typo, 感謝回報
