### ISSUE TITLE
Vector Section List(27%)

### ISSUE THREAD

**Issue by ningchencontact** [wush978/DataScienceAndR#40]
Vector的題目
g = lm(formula = dist ~ speed, data = cars)

我不太懂 以下的狀況(我猜這是我對lm 在list型態呈現不熟的關係)

g[1]
$coefficients
(Intercept) speed 
-17.579095 3.932409

g[2]
$residuals
1 2 3 4 5 6 7 8 9 10 
3.849460 11.849460 -5.947766 12.052234 2.119825 -7.812584 -3.744993 4.255007 12.255007 -8.677401 
11 12 13 14 15 16 17 18 19 20 
2.322599 -15.609810 -9.609810 -5.609810 -1.609810 -7.542219 0.457781 0.457781 12.457781 -11.474628 
21 22 23 24 25 26 27 28 29 30 
-1.474628 22.525372 42.525372 -21.407036 -15.407036 12.592964 -13.339445 -5.339445 -17.271854 -9.271854 
31 32 33 34 35 36 37 38 39 40 
0.728146 -11.204263 2.795737 22.795737 30.795737 -21.136672 -11.136672 10.863328 -29.069080 -13.069080 
41 42 43 44 45 46 47 48 49 50 
-9.069080 -5.069080 2.930920 -2.933898 -18.866307 -6.798715 15.201285 16.201285 43.201285 4.268876

g[3]
$effects
(Intercept) speed

-303.9144946 145.5522550 -8.1154395 9.8845605 0.1941147 -9.4963311 -5.1867770 2.8132230
10.8132230 -9.8772228 1.1227772 -16.5676686 -10.5676686 -6.5676686 -2.5676686 -8.2581144

-0.2581144 -0.2581144 11.7418856 -11.9485602 -1.9485602 22.0514398 42.0514398 -21.6390061

-15.6390061 12.3609939 -13.3294519 -5.3294519 -17.0198977 -9.0198977 0.9801023 -10.7103435

3.2896565 23.2896565 31.2896565 -20.4007893 -10.4007893 11.5992107 -28.0912352 -12.0912352

-8.0912352 -4.0912352 3.9087648 -1.4721268 -17.1625726 -4.8530184 17.1469816 18.1469816

45.1469816 6.4565358

g[4]
$rank
[1] 2

g[5]
$fitted.values
1 2 3 4 5 6 7 8 9 10 11 
-1.849460 -1.849460 9.947766 9.947766 13.880175 17.812584 21.744993 21.744993 21.744993 25.677401 25.677401 
12 13 14 15 16 17 18 19 20 21 22 
29.609810 29.609810 29.609810 29.609810 33.542219 33.542219 33.542219 33.542219 37.474628 37.474628 37.474628 
23 24 25 26 27 28 29 30 31 32 33 
37.474628 41.407036 41.407036 41.407036 45.339445 45.339445 49.271854 49.271854 49.271854 53.204263 53.204263 
34 35 36 37 38 39 40 41 42 43 44 
53.204263 53.204263 57.136672 57.136672 57.136672 61.069080 61.069080 61.069080 61.069080 61.069080 68.933898 
45 46 47 48 49 50 
72.866307 76.798715 76.798715 76.798715 76.798715 80.731124

**Comment by ChihChengLiang** [comment]
找不到課程這部份在哪QQ

**Comment by wush978** [comment]
@ChihChengLiang ，這應該是 https://github.com/wush978/DataScienceAndR/pull/35 的內容。歡迎幫我修改，XD
