### ISSUE TITLE
Console出現奇怪的文字

### ISSUE THREAD

**Issue by Stacy0531** [wush978/DataScienceAndR#425]
我在下完指令後, 不時會出現類似以下的文字,看起來是編碼的問題, 請問我要如何解決呢？
==== 以下是曾經遇過的一個例子====
 
| <U+57F7><U+884C><U+60A8><U+7684><U+6307><U+4EE4><U+78BC><U+4E2D>...

| All that hard work is paying off!

| <U+4F60><U+5DF2><U+7D93><U+5728><U+672C><U+8AB2><U+7A0B><U+7684><U+7D42><U+9EDE><U+4E86>!<U+6B63><U+5728><U+8FD4><U+56DE><U+4E3B><U+9078><U+55AE>...
Your status has beed updated to tracking server

| <U+4F60><U+9858><U+610F><U+5F9E><U+4E0B><U+9762><U+8AB2><U+7A0B><U+64C7><U+4E00><U+7E7C><U+7E8C><U+55CE>?

1: DataScienceAndR 01-RBasic-01-Introduction
2: 不，讓我開始一項新的課程

**Comment by wush978** [comment]
你重開後，載入swirl時，被詢問設定locale時選y


有幫助嗎？

**Comment by Stacy0531** [comment]
重開之後不會有問題, 可是到了上完課做作業, submit之後就出問題了

**Comment by wush978** [comment]
這很奇怪，我第一次聽到。

你的Ｒ是怎麼安裝的？有`sessionInfo()`的輸出結果嗎？

**Comment by Stacy0531** [comment]
很久之前裝的..不過我發現只要重開Ｒstudio並重新設定locale就好了, 我就先這樣處理吧, 謝謝
