### ISSUE TITLE
chapter 6 RBasic-06-List-DataFrame -- 建議

### ISSUE THREAD

**Issue by lovelybigdata** [wush978/DataScienceAndR#50]
(1)21% 修改多餘的字與錯字
因為list是個向量，所以我們過去學過得`[]`還是可以使用的。但是子向量的型態要和原本的向量相同，
所以如果我們運用如：`x[3]`的指令，從x 中選出只有包含第二個元素的向量，得到的輸出就會和`x`一樣是一個list。
--->
因為list是向量，所以我們過去學過的`[ ]`還能使用。所以如果我們運用 `x[3]` ，則從x 中選出第"三"個元素，得到的輸出就會和`x`一樣是一個list。簡言之， `class(x[1])`、 `class(x[2])`、`class(x[3])` 的結果都會是 list ，而  `class(x[[1]])`、 `class(x[[2]])`、`class(x[[3]])` 的結果則取決於原先生成 data.frame的資料型態； 請同學試試看：`mode(x[3])`

(2) 44% 刪除: "具體來說，data.frame就是一個表格" ，將其內容移至47%並新增說明文字

(3)47% 新增以下文字:
具體來說，data.frame就是一張"二維"表格，且只要求同一欄中(colunms)資料型態相同即可； 又或者我們可以把 data.frame 當成是 list 的特例(子集合)，以利於我們後續資料整處理與連接資料庫。  

(4)65% 更改舉例：
將原本的　`a <- data.frame(class = 1, id = 1:10)`可替換為
`a <- data.frame(class = "NTU", id = 1:10,scores = matrix(c(80:99),nrow=10,ncol=2 ) )` 
     理由：(a)多一個文字型態
                (b) scores 證明可放入 matrix 
                R 會自動幫忙把 scores 拆成 scores.1、scores.2(如下)，但實務上似乎比較少這樣做?
                (至少我沒遇過)
   class id scores.1 scores.2
1    NTU  1       80       90
2    NTU  2       81       91
3    NTU  3       82       92
4    NTU  4       83       93
5    NTU  5       84       94
6    NTU  6       85       95
7    NTU  7       86       96
8    NTU  8       87       97
9    NTU  9       88       98
10   NTU 10       89       99

(4)
其餘 "在windows上，如果名字是中文時，使用`$`的語法可能會出錯" → 
口頭鼓勵同學們儘量一般英文變數的命名慣例，以利未來將資料匯出至資料庫(例:sqlite … )

**Comment by wush978** [comment]
fixed!
