### ISSUE TITLE
chap7 RBasic-07-Loading-Dataset 建議

### ISSUE THREAD

**Issue by lovelybigdata** [wush978/DataScienceAndR#53]
(1)29% 與 80% 在 WIN10 與 LINUX(Docker) 都會出現疑似Bug的警告訊息，但不影響後續作答； 

29% 警告訊息:
warning messages from top-level task callback 'mini'
Warning message:
In stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE) :
  longer object length is not a multiple of shorter object length

80% 警告訊息:
warning messages from top-level task callback 'mini'
Warning messages:
1: closing unused connection 11 (/usr/local/lib/R/site-library/swirl/Courses/DataScienceAndR/RBasic-07-Loading-Dataset/A_LVR_LAND_A.CSV) 
2: closing unused connection 9 (/usr/local/lib/R/site-library/swirl/Courses/DataScienceAndR/RBasic-07-Loading-Dataset/A_LVR_LAND_A.CSV) 
3: closing unused connection 7 (/usr/local/lib/R/site-library/swirl/Courses/DataScienceAndR/RBasic-07-Loading-Dataset/A_LVR_LAND_A.CSV) 

(2) 20%說明文字調整

原文:
| 這就是`data`這個函數的功能。它可以讓同學從套件載入一個
| 資料集，並且會指定到第一個參數的變數名稱。舉例來說，在輸入： `data(iris, package = "datasets")`，R
| 會把一個名為iris的資料 集輸入到iris這個變數之中。

建議:
| 這就是`data`函數的功能，它可以讓同學從套件載入特定資料集(Data Sets)。
| 舉例來說，我們剛才已由`library(help=datasets)`觀察到 datasets套件中有包含許多資料集，
| 例如:AirPassengers、BJsales、…、iris…等
| 我們可用 `data(iris, package = "datasets")`指令，其中第一個參數可指定特定資料集，
| 則R會把iris的資料集輸入到iris這個變數之中。

(3) 40% 建議
原文 :
| csv 檔的格式是以列為單位。每一行檔案就是一列。而每一列中，
| 是以一個分隔符號來讓使用者或程式分辨欄位。常見的分隔符號有： tab (\t)或逗號(,) 。

建議:
| csv 檔的格式是以Line為單位。每一Line就是一筆紀錄(Record)。而每一筆紀錄中，
| 是以一個分隔符號來讓使用者或程式分辨欄位。常見的分隔符號有： tab (\t)或逗號(,) 。
| 若以逗號做為分隔符號，則學生姓名加上4次小考分數的一筆紀錄，可用CSV表達如下：
| 柯小哲,77,82,87,92

說明:
"行" 這個中文字很討厭，可以是 line 或是 row；
所以"每一行檔案就是一列"，這樣的說明文字，第一次看會覺得很迷惑??!! 
所以我自己於管理學院講資料庫概論時，我是直接用 row、columns、"欄位"、"紀錄"於課堂進行教學，
而避用中文的"行"、"列"。
另外中國的行列譯法剛好與我們相反，故建議直接用英文指稱，而非假裝 ABC；

**Comment by wush978** [comment]
Thanks!
