### ISSUE TITLE
chap. 7 作業部分出現錯誤訊息

### ISSUE THREAD

**Issue by CrystalTu** [wush978/DataScienceAndR#65]
warning messages from top-level task callback 'mini'
Warning message:
closing unused connection 4 (/Library/Frameworks/R.framework/Versions/3.1/Resources/library/swirl/Courses/DataScienceAndR/RBasic-07-Loading-Dataset/A_LVR_LAND_A.CSV)

**Comment by wush978** [comment]
@CrystalTu 感謝回報。

不過這是預期會發生的警告，不是錯誤，所以我就先不處理。
