### ISSUE TITLE
RBasic-05-Arrays-Matrices can not open

### ISSUE THREAD

**Issue by chinandy1991** [wush978/DataScienceAndR#75]
6: RBasic-05-Arrays-Matrices

開啟時會出現以下錯誤

Error in rbind(deparse.level, ...) : numbers of columns of arguments do not match

**Comment by wush978** [comment]
https://github.com/wush978/DataScienceAndR/commit/38a6a89554673fc5bccd8f85cd2623a4cb899794

fixed
