### ISSUE TITLE
敘述看不懂

### ISSUE THREAD

**Issue by kevin5826536** [wush978/DataScienceAndR#77]
在 RBasic-03-Data-Structure-Object 中，這段敘述怪怪的，看不懂。

| 這裡再解釋一次`g[1]`和`g[[1]]`的差異。使用`g[1]`時，使用者一個第一個值和`g[[1]]`一樣的list。
| 使用`g[[1]]`，使用者會取出第一個值，所以`g[[1]]`的型態就是`g`的第一個值的型態不同。
| 所以在上數的例子中，`g[1]`的型態是list，而`g[[1]]`的型態就是numeric。

**Comment by wush978** [comment]
謝謝回報，我再想想怎麼寫

**Comment by wush978** [comment]
@kevin5826536 

請問一下，你現在有搞懂這段文字的意思了嗎？還是我嘗試在這邊跟你作解釋呢？

**Comment by kevin5826536** [comment]
我應該已經了解了，謝謝~
