### ISSUE TITLE
RBasic-07-Loading-Dataset系統找不到指定的路徑

### ISSUE THREAD

**Issue by nellArM** [wush978/DataScienceAndR#78]
在選單下選擇8.RBasic-07-Loading-Dataset出現以下錯誤：
Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="C:/Users/Allen/Documents/R/win-library/3.2/swirl/Courses/DataScienceAndR/RBasic-07-Loading-Dataset/A_LVR_LAND_A.CSV": 系統找不到指定的路徑。

**Comment by nellArM** [comment]
目前有個暫時解法是在Courses/下建立DataScienceAndR的資料夾，然後把RBasic-07-Loading-Dataset/的東西全部移進去

**Comment by wush978** [comment]
慘，it works on my computer (win7)

請問重新安裝能不能解決呢？

**Comment by nellArM** [comment]
我重裝過後還是不行(我的系統是win10)

**Comment by wush978** [comment]
我想了想，覺得這應該是個bug。

但是目前我沒有環境可以重現這個錯誤，所以目前無法解決。先暫時記著。

**Comment by wush978** [comment]
@nellArM 還是感謝你提供的解法

**Comment by wush978** [comment]
由於無法重現，先暫時標記為 wontfix

**Comment by wush978** [comment]
因為issue越來越多，所以先把wontfix關閉。
