### ISSUE TITLE
Linux Mint 系統問題

### ISSUE THREAD

**Issue by luckytony** [wush978/DataScienceAndR#79]
我的 Linux Mint 15 有系統問題無法安裝R
我照這一頁的安裝指令輸入：http://cran.csie.ntu.edu.tw/bin/linux/debian/

主要是在這一個指令發生問題：apt-get install r-base r-base-dev
錯誤訊息是 404  Not Found [IP: 91.189.92.200 80]

他好像要我改好正確的 /etc/apt/sources.list 和改好正確的 mirror
但我不懂要怎麼改，我試了一些網路上的教學但也失敗了

直接使用這一行也失敗了：deb <favourite-cran-mirror>/bin/linux/debian wheezy-cran3/
不太清楚正確的 deb 的 /etc/apt/sources.list 應該怎麼改

有些教學好像是說作業系統沒有更新到最新版的問題
好像有說我的系統要先更新再來試著安裝，但是我輸入
    apt-get update 大部份成功，少數失敗，並顯示：
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/raring-updates/universe/binary-i386/Packages  404  Not Found [IP: 91.189.91.15 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
    apt-get upgrade 失敗，並顯示：
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/

問的不是swirl自學程式的問題，但我的 R 灌不起來，所以PO在這裡問
感謝！

**Comment by wush978** [comment]
不好意思，source.list的部份應該是適用於ubuntu/debian

我自己沒有使用過Linux Mint, 而且R 的CRAN只提供debian、ubuntu、suse和redhat上的binary。所以你可能要安裝編譯器自己編譯。

我建議在安裝相關工具之後，下載 R 的 source http://cran.csie.ntu.edu.tw/src/base/R-3/R-3.2.2.tar.gz 之後，解壓縮，然後：

```
./configure --with-blas --with-lapack --enable-R-shlib --enable-BLAS-shlib --enable-memory-profiling
make
make install
```

./configure可以開啟一些選項，但是也需要額外的函式庫。
具體還是要看你的環境...

抱歉，我最近沒空裝VM來看，所以可能要麻煩你先自己解決看看了。

**Comment by wush978** [comment]
@luckytony 

請問後來你有成功的架設出做作業的環境嗎？

**Comment by luckytony** [comment]
@wush978 
sorry這麼晚回
我後來直接使用Windows的RStudio了
因為我不太懂
