### ISSUE TITLE
How to browse homework w/ R or RStudio ?

### ISSUE THREAD

**Issue by yujianyuanhaha** [wush978/DataScienceAndR#81]
Sorry about the skip of Data Science class of NTU last week, it seems I miss sth important.
I've seen the slides, and install R and RStudio(Mac OS X EI), and swirl and install class goes well.
<img width="678" alt="screen shot 2015-10-25 at 1 07 15 pm" src="https://cloud.githubusercontent.com/assets/9403813/10714143/62896452-7b19-11e5-8a47-9a2ad39ef4e4.png">
But how can I see the content of class and homework? Is it in RStudio ?

**Comment by yujianyuanhaha** [comment]
well, I've found the file by the prompt message at PATH : '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/swirl/Courses/DataScienceAndR'
but I guess I still use it in the wrong way

**Comment by wush978** [comment]
Enter `swirl()` and pick the course `DataScienceAndR`. 

Then you could choose the lesson and accomplish the assignments.

**Comment by yujianyuanhaha** [comment]
yep, tx a lot for ur kind and patient reply.
Actually I mistook the '再次進入swirl' as 'library(swirl)' at slides 55/61, maybe u can make it more clear.
Also, after browse the .R and .yaml file, the script grammer seems simple and elegant, I guess I can keep a swirl class sometime ^ ^.

**Comment by wush978** [comment]
I update the README of this project to explain the swirl course.

Hope that helps.
