### ISSUE TITLE
RBasic-00 目前長期失效

### ISSUE THREAD

**Issue by wush978** [wush978/DataScienceAndR#85]
自從某日開始，RBasic-00就失效至今。

可能需要尋找新的範例資料集，以及把RBasic-00從課程清單中先移除。

**Comment by yujianyuanhaha** [comment]
Yep, And how can we skip the bug and go on to RBasic_01  > <
U cannot believe it I'm reading .src.yaml file now.

**Comment by wush978** [comment]
@yujianyuanhaha 
Just select the course Basic-01 at the beginning of the swirl. Please follow the instruction in https://github.com/wush978/DataScienceAndR/blob/master/README.md

**Comment by yujianyuanhaha** [comment]
yep, I got it
![image](https://cloud.githubusercontent.com/assets/9403813/10818065/81a66dae-7e79-11e5-859b-c5c717476738.png)

**Comment by wush978** [comment]
#105
