### ISSUE TITLE
RStudio (Mac) 無法顯示中文

### ISSUE THREAD

**Issue by wush978** [wush978/DataScienceAndR#86]
今天的R Ladies上有人遇到相關問題。

請她確認：https://github.com/TaiwanRUserGroup/DSC2015Tutorial/wiki/Q&A#rstudio-mac-%E7%84%A1%E6%B3%95%E9%A1%AF%E7%A4%BA%E4%B8%AD%E6%96%87能否解決她的問題中。

**Comment by yujianyuanhaha** [comment]
http://stackoverflow.com/questions/9689104/installing-r-on-mac-warning-messages-setting-lc-ctype-failed-using-c
1. Open Terminal
2. Write or paste in: defaults write org.R-project.R force.LANG en_US.UTF-8
3. Close Terminal
4. Start R
It works fine for me.

**Comment by wush978** [comment]
Thanks!
