### ISSUE TITLE
''perl is deprecated. Please use regexp instead". Please help to fix!

### ISSUE THREAD

**Issue by lky880154** [wush978/DataScienceAndR#87]
/> install_course_github("wush978", "DataScienceAndR", "course")
perl is deprecated. Please use regexp instead
Warning message:
In file.rename(file.path(system.file(package = "swirl"), "Courses",  :
  cannot rename file '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/swirl/Courses/wush978-DataScienceAndR-aa661ec' to '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/swirl/Courses/DataScienceAndR', reason 'Directory not empty'

> /> sessionInfo()
> R version 3.2.2 (2015-08-14)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.11.1 (El Capitan)
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] curl_0.9.1   swirl_2.2.21
> 
> loaded via a namespace (and not attached):
>  [1] httr_1.0.0      R6_2.1.0        magrittr_1.5    tools_3.2.2     RCurl_1.95-4.7  yaml_2.1.13     memoise_0.2.1   crayon_1.3.1    stringi_0.5-5   stringr_1.0.0  
> [11] digest_0.6.8    testthat_0.10.0 bitops_1.0-6

**Comment by wush978** [comment]
@lky880154 

能不能麻煩你先執行：

```
library(swirl)
delete_progress("<user>")  # 請把<user>換成練習 swirl 時用的名字，Ex. wush。如果都沒用過，可以跳過
uninstall_all_courses()
install_course_github("wush978", "DataScienceAndR", "course")
```

然後如果還是出現 `Perl...`開頭的紅色字眼，請先略過。直接進入`swirl()`看看課程是否安裝成功。

謝謝回報

**Comment by lky880154** [comment]
@wush978 

謝謝您的迅速回覆！

請問這樣是成功了嗎？
/> swirl()

| Welcome to swirl!

| Please sign in. If you've been here before, use the same name as you did then. If you are new, call yourself something unique.

**Comment by wush978** [comment]
還沒。

請參考 https://github.com/wush978/DataScienceAndR#%E9%80%B2%E5%85%A5%E8%AA%B2%E7%A8%8B 底下的範例圖示操作，看看會不會跳出`DataScienceAndR`的課程。

**Comment by lky880154** [comment]
@wush978 

這樣應該可以了？

Selection: 2

  |                                                                                                                          |   0%

| 這門課程要讓大家透過互動式的內容，上手R 語言。

...

  |====                                                                                                                      |   3%

| 這份文件中的格式採用和Markdown相容的語法。 為了讓大家快速上手，這裡先說明一些常見的Markdown語法
| 所有的程式碼，都會用``來包覆。例如：當swirl提示要各位輸入：`sessionInfo()` 就代表各位同學要在console輸入：sessionInfo()

**Comment by wush978** [comment]
是的。
