### ISSUE TITLE
RBasic-06-HW.R X, y for answer11

### ISSUE THREAD

**Issue by lky880154** [wush978/DataScienceAndR#89]
我如果自己在Console做 tmp <- model.matrix(~ Type + Treatment + conc, CO2)
結果如下：

> /> tmp
>    (Intercept) TypeMississippi Treatmentchilled conc
> 1            1               0                0   95
> 2            1               0                0  175
> 3            1               0                0  250
> 4            1               0                0  350
> 5            1               0                0  500
> 6            1               0                0  675
> 7            1               0                0 1000
> 8            1               0                0   95
> 9            1               0                0  175
> 10           1               0                0  250
> 11           1               0                0  350
> 12           1               0                0  500
> 13           1               0                0  675
> 14           1               0                0 1000
> 15           1               0                0   95
> 16           1               0                0  175
> 17           1               0                0  250
> 18           1               0                0  350
> 19           1               0                0  500
> 20           1               0                0  675
> 21           1               0                0 1000
> 22           1               0                1   95
> 23           1               0                1  175
> 24           1               0                1  250
> 25           1               0                1  350
> 26           1               0                1  500
> 27           1               0                1  675
> 28           1               0                1 1000
> 29           1               0                1   95
> 30           1               0                1  175
> 31           1               0                1  250
> 32           1               0                1  350
> 33           1               0                1  500
> 34           1               0                1  675
> 35           1               0                1 1000
> 36           1               0                1   95
> 37           1               0                1  175
> 38           1               0                1  250
> 39           1               0                1  350
> 40           1               0                1  500
> 41           1               0                1  675
> 42           1               0                1 1000
> 43           1               1                0   95
> 44           1               1                0  175
> 45           1               1                0  250
> 46           1               1                0  350
> 47           1               1                0  500
> 48           1               1                0  675
> 49           1               1                0 1000
> 50           1               1                0   95
> 51           1               1                0  175
> 52           1               1                0  250
> 53           1               1                0  350
> 54           1               1                0  500
> 55           1               1                0  675
> 56           1               1                0 1000
> 57           1               1                0   95
> 58           1               1                0  175
> 59           1               1                0  250
> 60           1               1                0  350
> 61           1               1                0  500
> 62           1               1                0  675
> 63           1               1                0 1000
> 64           1               1                1   95
> 65           1               1                1  175
> 66           1               1                1  250
> 67           1               1                1  350
> 68           1               1                1  500
> 69           1               1                1  675
> 70           1               1                1 1000
> 71           1               1                1   95
> 72           1               1                1  175
> 73           1               1                1  250
> 74           1               1                1  350
> 75           1               1                1  500
> 76           1               1                1  675
> 77           1               1                1 1000
> 78           1               1                1   95
> 79           1               1                1  175
> 80           1               1                1  250
> 81           1               1                1  350
> 82           1               1                1  500
> 83           1               1                1  675
> 84           1               1                1 1000
> attr(,"assign")
> [1] 0 1 2 3
> attr(,"contrasts")
> attr(,"contrasts")$Type
> [1] "contr.treatment"
> 
> attr(,"contrasts")$Treatment
> [1] "contr.treatment"

但是執行

> />submit()
> />X
>       x1 x2         x3
>  [1,]  1  1  0.8414710
>  [2,]  1  2  0.9092974
>  [3,]  1  3  0.1411200
>  [4,]  1  4 -0.7568025
>  [5,]  1  5 -0.9589243
>  [6,]  1  6 -0.2794155
>  [7,]  1  7  0.6569866
>  [8,]  1  8  0.9893582
>  [9,]  1  9  0.4121185
> [10,]  1 10 -0.5440211

y也是一樣的問題
請問這是為什麼呢？

謝謝

**Comment by lky880154** [comment]
我後來改成
y <- CO2[["uptake"]]
就過了

**Comment by wush978** [comment]
請問題目上是不是有讓你覺得不清楚的地方？

**Comment by lky880154** [comment]
我以為是要寫
y <- model.matrix(~ update, CO2)
