### ISSUE TITLE
無法載入library(swirl)

### ISSUE THREAD

**Issue by stopstoptalking** [wush978/DataScienceAndR#90]
wush大大您好:

我用同一台電腦, 在課堂上及幾前天都可以按照網頁上的步驟進入swirl學習R及寫作業，
但是今天打開R時，輸入library(swirl)卻出現下面訊息:

> library(swirl)
> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
>   there is no package called ‘stringi’
> Error: package or namespace load failed for ‘swirl’

我重新安裝套件後, 只有以下東西被安裝了:

R version 3.2.0 (2015-04-16) -- "Full of Ingredients"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(swirl)
> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
>   there is no package called ‘stringi’
> Error: package or namespace load failed for ‘swirl’
> remove.packages(swirl)
> Error in remove.packages : object 'swirl' not found
> remove.packages(swirl)
> Error in remove.packages : object 'swirl' not found
> remove.packages(swirl)
> Error in remove.packages : object 'swirl' not found
> install.packages('swirl', repos = 'http://taiwanrusergroup.github.io/R')
> Installing package into ‘C:/Users/CDBTM/Documents/R/win-library/3.2’
> (as ‘lib’ is unspecified)
> trying URL 'http://taiwanrusergroup.github.io/R/bin/windows/contrib/3.2/swirl_2.3.1.zip'
> Content type 'application/zip' length 146194 bytes (142 KB)
> downloaded 142 KB

The downloaded binary packages are in
    C:\Users\CDBTM\AppData\Local\Temp\RtmpAPPtAR\downloaded_packages

> library(swirl)

然後再次輸入library(swirl)也是和上面一樣的結果(找不到stringi). 我想把swirl移除, 但系統說我沒有這個東西.

> remove.packages(swirl)
> Error in remove.packages : object 'swirl' not found

這是我的sessionInfo

> library(swirl)
> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
>   there is no package called ‘stringi’
> Error: package or namespace load failed for ‘swirl’
> sessionInfo()
> R version 3.2.0 (2015-04-16)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Chinese (Traditional)_Taiwan.950 
[2] LC_CTYPE=Chinese (Traditional)_Taiwan.950  
[3] LC_MONETARY=Chinese (Traditional)_Taiwan.950
[4] LC_NUMERIC=C  
[5] LC_TIME=Chinese (Traditional)_Taiwan.950    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.0    RCurl_1.95-4.7 digest_0.6.8   bitops_1.0-6  

請問我該怎麼解決呢? 
PS: 如果是我個人的問題, 我再找一台電腦做作業就好

**Comment by wush978** [comment]
@stopstoptalking 

要不要先更新R到3.2.2，然後重新裝一次swirl和課程呢？

更新之後，請執行：

``` r
install.packages('swirl', repos = 'http://taiwanrusergroup.github.io/R')
library(swirl)
library(curl) # 如果套件載入失敗，請先安裝：`install.packages("curl") `
install_course_github("wush978", "DataScienceAndR", "course")
```

**Comment by stopstoptalking** [comment]
感謝wush大大迅速地回覆. (我發現我的貼文貼得很亂, 真是抱歉)
我移除舊的R, 安裝3.2.2版後, 仍舊出現一樣的error訊息,

> library(swirl)
> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
>   there is no package called ‘stringi’
> Error: package or namespace load failed for ‘swirl’

所以我就手動安裝"stringi"這個package

> install.packages('stringi',repos = 'http://taiwanrusergroup.github.io/R')
> Installing package into ‘C:/Users/CDBTM/Documents/R/win-library/3.2’
> (as ‘lib’ is unspecified)
> trying URL 'http://taiwanrusergroup.github.io/R/bin/windows/contrib/3.2/stringi_0.5-5.zip'
> Content type 'application/zip' length 14261819 bytes (13.6 MB)
> downloaded 13.6 MB

然後就可以進 swirl 囉!!

(ps: 雖然斷斷續續用R十幾年了, 透過這次的教學檔還是學到很多東西, 謝謝!)

**Comment by wush978** [comment]
感謝你的回報。有興趣的話，歡迎加入貢獻者團隊... XD

這個專案需要大量的寫手和測試，有興趣歡迎私下接洽。

我先關閉這個issue（看起來升級R + 重新安裝需要的套件有用），有其他問題再麻煩你開issue 。
