### ISSUE TITLE
How to ensure I'v finish all the homework

### ISSUE THREAD

**Issue by yujianyuanhaha** [wush978/DataScienceAndR#91]
![image](https://cloud.githubusercontent.com/assets/9403813/10851931/cfeae068-7f68-11e5-8ed1-e6382cb6808f.png)
well, I happens find there are duplicate courses, I don't remember which course I take in, sometimes I finish the homework in Course 'DataScienceAndR' while sometimes I'm on the latter.
Does it means I've to remove the file and run through the course again > < .

**Comment by wush978** [comment]
I think the assignment is clearly defined in the slide: http://www.slideshare.net/WushWu/r-54273044

Please indicate which part/page of the slide is unclear so that you cannot understand the assignment.
