### ISSUE TITLE
RBasic-07-Loading-Dataset warning message

### ISSUE THREAD

**Issue by poyuwu** [wush978/DataScienceAndR#92]
在離開swirl之後會有以下warning message:(readlines也有)
「
最高層任務回呼 'mini' 產生了警告訊息
Warning message:
關閉未使用的連接 4 (/Library/Frameworks/R.framework/Versions/3.2/Resources/library/swirl/Courses/DataScienceAndR/RBasic-07-Loading-Dataset/orglist-100.CSV) 
」

想問一下這可能是什麼原因造成的?

**Comment by wush978** [comment]
Hi @poyuwu :

這是R 在開檔案的時候，開啟的檔案handle被gc關閉的警告訊息。

如果沒有手動關閉檔案handle的話，就會有類似的訊息。
